SET NAMES 'utf8';

UPDATE `dbscript_string` SET `content_loc3`='Danke, $N Und viel Glück!' WHERE (`entry`='2000000000'); /* content: Thank you, $N. And luck to you. */
UPDATE `dbscript_string` SET `content_loc3`='Die Klippenquellfälle befinden sich in den Bergen Richtung Osten und Norden.' WHERE (`entry`='2000000001'); /* Cliffspring Falls lies along the mountains to the east and north. */
UPDATE `dbscript_string` SET `content_loc3`='Geht rasch, $N Mein Schicksal liegt in Eurer Hand.' WHERE (`entry`='2000000002'); /* Go swiftly $N. My fate is in your hands. */
UPDATE `dbscript_string` SET `content_loc3`='Großmutter Falkenwind deutet auf die Wasserkanne, die auf dem Rand des Brunnens steht.' WHERE (`entry`='2000000003'); /* %s gestures to the pitcher of water sitting on the edge of the well. */
UPDATE `dbscript_string` SET `content_loc3`='Es ist lange her, Bethor, mein Freund.' WHERE (`entry`='2000000004'); /* It has been a long time, Bethor, my friend. */
UPDATE `dbscript_string` SET `content_loc3`='Wenn es die Zeit erlaubt, dann müssen wir uns in Ruhe unterhalten, denn wir haben viel zu besprechen.' WHERE (`entry`='2000000005'); /* When time permits, we must speak at length. For we have much to discuss. */
UPDATE `dbscript_string` SET `content_loc3`='Und danke, $N Ohne Eure Hilfe hätte ich den Weg zu den Verlassenen nie gefunden.' WHERE (`entry`='2000000006'); /* And thank you, $N.  Without your aid I may never have found my way to the Forsaken. */
UPDATE `dbscript_string` SET `content_loc3`='Lebt wohl, mein Freund.' WHERE (`entry`='2000000007'); /* Farewell, my friend. */
UPDATE `dbscript_string` SET `content_loc3`='%s schnuppert an dem Elixier und langt dann eifrig zu!' WHERE (`entry`='2000000008'); /* %s sniffs the elixir then eagerly digs in! */
UPDATE `dbscript_string` SET `content_loc3`='Ah, das ist genau richtig! Ich glaube, ich hole mir noch ein paar... könnt Ihr für mich auf diese Fässer aufpassen, $N' WHERE (`entry`='2000000012'); /* Ah, that sure does hit the spot! I think i\'ll get myself a couple more...can you watch these barrels for me, $N? */
UPDATE `dbscript_string` SET `content_loc3`='Und wie läuft das Fassbewachen...?' WHERE (`entry`='2000000013'); /* How goes the barrel watching...? */
UPDATE `dbscript_string` SET `content_loc3`='Nun ja, ich muss mich wieder um die Arbeit kümmern. Aber so eine kleine Pause tut schon gut und so ein Donnerbräu Lager schmeckt immer!' WHERE (`entry`='2000000014'); /* Well, back to business for me. But it sure was nice taking that short break, and it\'s always nice drinking Thunder Ale! */
UPDATE `dbscript_string` SET `content_loc3`='Ich danke Euch, $n. Und mein Bruder dankt Euch ebenfalls.' WHERE (`entry`='2000000016'); /* I thank you. $n. And my brother thanks you. */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt zu singen, während er die Quellsteine und das Bernsteinkorn vor dem Stammesfeuer vermischt.' WHERE (`entry`='2000000017'); /* %s begins chanting as he mixes the well stones and ambercom before the Tribal Fire. */
UPDATE `dbscript_string` SET `content_loc3`='Das Wasser der Seher steht für Euch zum Trinken bereit, $N' WHERE (`entry`='2000000018'); /* The Water of the Seers is ready for your consumption, $N. */
UPDATE `dbscript_string` SET `content_loc3`='Habt Geduld, $N. Die Fackel ist fast fertig.' WHERE (`entry`='2000000019'); /* Be patient $N. The torch is almost complete. */
UPDATE `dbscript_string` SET `content_loc3`='Das ist interessant...' WHERE (`entry`='2000000020'); /* That\'s interesting... */
UPDATE `dbscript_string` SET `content_loc3`='Ich muss Noram und Horatio kontaktieren.' WHERE (`entry`='2000000021'); /* I need to consult Noram and Horatio. */
UPDATE `dbscript_string` SET `content_loc3`='Geht jetzt, $N. Findet Volcor... und denkt daran, dass die Magie, die Euch beschützt, versagen wird, wenn Ihr mit anderen mehr tut als bloß zu reden.' WHERE (`entry`='2000000022'); /* Go now, $N. Find Volcor... and remember, the magics protecting you will fail if you interact with anyone, save for talking. */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt, einen Zauber zu wirken, als Ihr ihm den Umhang abnehmt.' WHERE (`entry`='2000000023'); /* %s begins to cast a spell as you take the cloak from him. */
UPDATE `dbscript_string` SET `content_loc3`='M... m... mir... geht... es... nicht... gut...' WHERE (`entry`='2000000024'); /* %s I. . .I. . .don\'t. . .feel. . .right. . . */
UPDATE `dbscript_string` SET `content_loc3`='Mein Verstand... mein Fleisch... ich... verwese...!' WHERE (`entry`='2000000025'); /* My mind. . .my flesh. . .I\'m. . .rotting. . . .! */
UPDATE `dbscript_string` SET `content_loc3`='Ups!' WHERE (`entry`='2000000026'); /* Whoops! */
UPDATE `dbscript_string` SET `content_loc3`='Das Volk von Westfall salutiert vor $N, einem mutigen und tapferen Verteidiger der Freiheit.' WHERE (`entry`='2000000028'); /* The People of Westfall salute $N, a brave and valiant defender of freedom. */
UPDATE `dbscript_string` SET `content_loc3`='Das macht Sinn!' WHERE (`entry`='2000000030'); /* This makes sense! */
UPDATE `dbscript_string` SET `content_loc3`='Vorsicht, $n! Schaut nach Westen!' WHERE (`entry`='2000000031'); /* Beware, $n! Look to the west! */
UPDATE `dbscript_string` SET `content_loc3`='Seid gewappnet, $N, denn der Dämon in dieser Kugel ist eine Teufelsbestie.' WHERE (`entry`='2000000032'); /* Gird yourself $N, for the demon in this orb is a fel beast. */
UPDATE `dbscript_string` SET `content_loc3`='%s beschwört einen Boten...' WHERE (`entry`='2000000033'); /* %s summons a messenger... */
UPDATE `dbscript_string` SET `content_loc3`='Lass mich dir dabei helfen.' WHERE (`entry`='2000000034'); /* Let me help you with those. */
UPDATE `dbscript_string` SET `content_loc3`='Trink das, es wird dir helfen' WHERE (`entry`='2000000035'); /* Drink this, it will help. */
UPDATE `dbscript_string` SET `content_loc3`='Dir wird es gut gehen' WHERE (`entry`='2000000036'); /* You\'re going to be just fine. */
UPDATE `dbscript_string` SET `content_loc3`='Bis wir uns wiedersehen, tapfere Seele.' WHERE (`entry`='2000000042'); /* Until we meet again, brave one. */
UPDATE `dbscript_string` SET `content_loc3`='Es ist vollbracht...' WHERE (`entry`='2000000044'); /* It is done... */
UPDATE `dbscript_string` SET `content_loc3`='Es geht doch nichts über kochend heißes Morgengebräu an einem kalten Morgen in Dun Morogh! Danach kann der Tag kommen!' WHERE (`entry`='2000000045'); /* There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right! */
UPDATE `dbscript_string` SET `content_loc3`='Ooooh! Heiß! Heiß! Heiß! Wenn Euch das nicht auf Touren bringt, kann ich Euch auch nicht helfen!' WHERE (`entry`='2000000046'); /* Oooooo hot hot hot! If that won\'t put spring IN your step,I don\'t know what will! */
UPDATE `dbscript_string` SET `content_loc3`='Verflixt! Nein!!! Das kann... verflixt... nicht sein! Ihr habt mich... verflixt... mit Euren faulen Tricks betrogen! Verflixt!' WHERE (`entry`='2000000047'); /* Ribbit! No!! This cannot... ribbit... be! You have duped me with... ribbit... your foul trickery! Ribbit! */
UPDATE `dbscript_string` SET `content_loc3`='Lasst uns nun diese seltene Erde in meinen Pflanzbehälter füllen...' WHERE (`entry`='2000000048'); /* Now let us place this rare earth in my planter... */
UPDATE `dbscript_string` SET `content_loc3`='Ich danke Euch nochmals, $N. Diese seltene Erde wird mir bei meinen Experimenten von großem Nutzen sein.' WHERE (`entry`='2000000049'); /* Thank you again, $N. This rare earth will be very helpful in my experiments. */
UPDATE `dbscript_string` SET `content_loc3`='Hey, Belm! Gib mir einen Becher Donnerbräu Lager und einen für meinen guten Freund $N.' WHERE (`entry`='2000000056'); /* Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N. */
UPDATE `dbscript_string` SET `content_loc3`='Geister des Wassers, ich preise euch und erflehe einen Gefallen von euch. Ihr habt die Bitten gehört, die $N an euch gerichtet hat, und ich bin mir sicher, ihre Beweggründe sind lauter und edel. Bitte, helft uns.' WHERE (`entry`='2000000057'); /* Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s please, and I trust his inent is noble. Please, will you aid us? */
UPDATE `dbscript_string` SET `content_loc3`='Dank Euch, großer Geist. Danke!' WHERE (`entry`='2000000058'); /* Thank you great spirit. Thank you! */
UPDATE `dbscript_string` SET `content_loc3`='Ihr seid entlassen, $n.' WHERE (`entry`='2000000059'); /* You are dismissed, $N. */
UPDATE `dbscript_string` SET `content_loc3`='Folgt mir, guter $C. Ich werde Euer Pferdegeschirr schneller fertigen, als ich ein Zwergen - Starkbier hinunterspülen kann. Mmmm.... Starkbier.' WHERE (`entry`='2000000063'); /* Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout. */
UPDATE `dbscript_string` SET `content_loc3`='Nun, das sollte ausreichen. Komm jetzt, lasst uns zurück zum Laden gehen, um das Geschäft zu beenden!' WHERE (`entry`='2000000064'); /* Well, that should do it. Come now, back to the shop to finish our business! */
UPDATE `dbscript_string` SET `content_loc3`='Wir werden keinen Dämonen-Diener in unseren Ländern dulden!' WHERE (`entry`='2000000065'); /* We will suffer no demon\'s servant in our lands! */
UPDATE `dbscript_string` SET `content_loc3`='Friede und Geduld sei mit Euch, $N. Bleibt immer stark.' WHERE (`entry`='2000000066'); /* Peace and patience be with you, $N. Remain strong always. */
UPDATE `dbscript_string` SET `content_loc3`='%s versucht, Maurys Klumpfuß zu öffnen...' WHERE (`entry`='2000000067'); /* %s tries opening Maury\'s Clubbed Foot... */
UPDATE `dbscript_string` SET `content_loc3`='Pah! $N, dieser Fuß gibt nicht nach!' WHERE (`entry`='2000000068'); /* Bah! $N, this foot won\'t budge! */
UPDATE `dbscript_string` SET `content_loc3`='Danke, $N.' WHERE (`entry`='2000000069'); /* Thank you, $N. */
UPDATE `dbscript_string` SET `content_loc3`='Ich bin sicher, dass ich eine Verwendung für diese Mixtur finden werde...' WHERE (`entry`='2000000070'); /* I\'m sure I can find a use for this mixture... */
UPDATE `dbscript_string` SET `content_loc3`='Nochmals vielen Dank für Ihre Hilfe. Möge der Wind während Ihrer Reisen immer in Ihrem Rücken sein' WHERE (`entry`='2000000071'); /* Thank you again for your aid. May the wind always be at your back during your travels. */
UPDATE `dbscript_string` SET `content_loc3`='Das war einfacher als ich dachte... das Siegelzeichen von Thoradin ist endlich wieder ganz.' WHERE (`entry`='2000000072'); /* Easier than I expected... the sigil of Thoradin is whole, once again. */
UPDATE `dbscript_string` SET `content_loc3`='Wartet, $N!!! Es sieht so aus, als würden wir hier Hilfe brauchen...' WHERE (`entry`='2000000073'); /* Wait, $N!!! It looks like we\'re going to need some help here... */
UPDATE `dbscript_string` SET `content_loc3`='In den Kasten, meine Süßen! Genau so. Einer nach dem anderen.' WHERE (`entry`='2000000074'); /* Into the box me pretties! Thas it. One by one, ye go. */
UPDATE `dbscript_string` SET `content_loc3`='Hört her, Bewohner von Tanaris! Ihr sollt wissen, dass $n ein erhabenes Mitglied des Mithrilordens ist. Ein Schmied von Ehre, Hingabe und unendlicher Geduld. Ein dreifaches Hoch auf $n!' WHERE (`entry`='2000000076'); /* Hear ye, denizens of Tanaris! Let it be known $n is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $n */
UPDATE `dbscript_string` SET `content_loc3`='Hört her, Bewohner von Tanaris! Ihr sollt wissen, dass $n ein erhabenes Mitglied des Mithrilordens ist. Ein Schmied von Ehre, Hingabe und unendlicher Geduld. Ein dreifaches Hoch auf $n%s spürt, wie sein Blut in Wallung gerät und die Arglist des Raptors ihn durchströmt.' WHERE (`entry`='2000000077'); /* %s watches as his blood begins to stir, and the guile of the raptor slips through him. */
UPDATE `dbscript_string` SET `content_loc3`='Was ist das für eine Stärke, die mich durchfließt? Ist dies die Macht des Schamanismus, von der Torgan gesprochen hat...?' WHERE (`entry`='2000000078'); /* What is this power that flows through me? Is this the power of shamanism that Tor\'gan spoke of...? */
UPDATE `dbscript_string` SET `content_loc3`='Beeindruckend! Ich fühle mich... erneuert. Meine Kraft kehrt zurück!' WHERE (`entry`='2000000079'); /* Amazing! I feel... renewed. My strength returns! */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt einen Ritus der Erschaffung...' WHERE (`entry`='2000000080'); /* %s begins a rite of creation... */
UPDATE `dbscript_string` SET `content_loc3`='Ich habe das Totem erschaffen. Ihr, $N, müsst den Brunnen läutern.' WHERE (`entry`='2000000081'); /* I have created the totem. You, $N, must cleanse the well. */
UPDATE `dbscript_string` SET `content_loc3`='%s erschafft ein neues Totem...' WHERE (`entry`='2000000082'); /* %s creates a new totem... */
UPDATE `dbscript_string` SET `content_loc3`='Das Totem ist fertig, $N.' WHERE (`entry`='2000000083'); /* The totem is made, $N. */
UPDATE `dbscript_string` SET `content_loc3`='%s verwandelt die Gegenstände von $n in ein Totem der Läuterung...' WHERE (`entry`='2000000084'); /* %s transforms the items $N gave him into a totem of cleansing... */
UPDATE `dbscript_string` SET `content_loc3`='Das Totem ist fertig. Der Brunnen kann nun geläutert werden.' WHERE (`entry`='2000000085'); /* The totem is made. The well may now be cleansed. */
UPDATE `dbscript_string` SET `content_loc3`='%s betrachtet das Pergament aus dem Folianten der Schattenhammerkultisten...' WHERE (`entry`='2000000086'); /* %s studies the parchment from the Twilight Tome... */
UPDATE `dbscript_string` SET `content_loc3`='%s wird von freigesetzter Magie getroffen!' WHERE (`entry`='2000000087'); /* %s is struck by unleashed magic! */
UPDATE `dbscript_string` SET `content_loc3`='Hmmm...' WHERE (`entry`='2000000088'); /* Hmm... */
UPDATE `dbscript_string` SET `content_loc3`='Die Geister des Steinkrallengebirges wüten noch immer, $n.' WHERE (`entry`='2000000089'); /* The spirits of Stonetalon still rage, $N. */
UPDATE `dbscript_string` SET `content_loc3`='Ich fürchte, wir werden sie niemals beschwichtigen können...' WHERE (`entry`='2000000090'); /* I fear we may never soothe them... */
UPDATE `dbscript_string` SET `content_loc3`='%s hört sich die Bitte von $n an.' WHERE (`entry`='2000000091'); /* %s listens to $N\'s plea. */
UPDATE `dbscript_string` SET `content_loc3`='Ihr habt gut daran getan zu kommen. Meine Weisheit gehört Euch.' WHERE (`entry`='2000000092'); /* You were right to come. My wisdom will be yours. */
UPDATE `dbscript_string` SET `content_loc3`='Geht, mein Diener. Bringt Kunde vom Steinkrallengebirge zu Apothekerin Zamah.' WHERE (`entry`='2000000093'); /* Go, my servant. Send word of Stonetalon to Apothecary Zamah. */
UPDATE `dbscript_string` SET `content_loc3`='%s übergibt Apothekerin Zamah eine Nachricht.' WHERE (`entry`='2000000094'); /* %s gives message to Apothecary Zamah. */
UPDATE `dbscript_string` SET `content_loc3`='%s lächelt.' WHERE (`entry`='2000000095'); /* %s smiles. */
UPDATE `dbscript_string` SET `content_loc3`='%s erschafft sein Toxin...' WHERE (`entry`='2000000096'); /* %s creates his toxin... */
UPDATE `dbscript_string` SET `content_loc3`='Da wären wir, $n. Das Toxin steht bereit.' WHERE (`entry`='2000000097'); /* There we are, $N. The toxin is ready. */
UPDATE `dbscript_string` SET `content_loc3`='%s füllt einen Behälter mit dem Toxin.' WHERE (`entry`='2000000098'); /* %s fills a container with the toxin. */
UPDATE `dbscript_string` SET `content_loc3`='Das Toxin ist fertig, $n.' WHERE (`entry`='2000000099'); /* %s The toxin is ready, $N. */
UPDATE `dbscript_string` SET `content_loc3`='%s stellt die Kiste mit den Teilen auf den Boden.' WHERE (`entry`='2000000100'); /* %s places the crate of parts on the ground. */
UPDATE `dbscript_string` SET `content_loc3`='%s greift sich ein Teil und steckt es in die Tasche...' WHERE (`entry`='2000000101'); /* %s grabs a part and puts it in his pocket... */
UPDATE `dbscript_string` SET `content_loc3`='So, das sollte reichen...' WHERE (`entry`='2000000102'); /* There, that should do it... */
UPDATE `dbscript_string` SET `content_loc3`='%s saugt etwas Traumstaub in die Nase...' WHERE (`entry`='2000000103'); /* %s snorts a speck of dream dust up his nose... */
UPDATE `dbscript_string` SET `content_loc3`='%s ist benommen...' WHERE (`entry`='2000000104'); /* %s is dazed... */
UPDATE `dbscript_string` SET `content_loc3`='HATSCHI!' WHERE (`entry`='2000000105'); /* ACHOO! */
UPDATE `dbscript_string` SET `content_loc3`='Unglaublich! $n, dieser Traumstaub ist aber ein Teufelszeug!' WHERE (`entry`='2000000106'); /* Wow! $N, that dream dust is powerful stuff! */
UPDATE `dbscript_string` SET `content_loc3`='He, $n! Vergesst nicht, eine Kiste, ein Handbuch und einen Leitstecken mitzunehmen!' WHERE (`entry`='2000000107'); /* Hey $N! Don\'t forget to grab a crate, a manual and a command stick! */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt zu tanzen.' WHERE (`entry`='2000000108'); /* %s begins to dance. */
UPDATE `dbscript_string` SET `content_loc3`='Haha! $n, Ihr seid mir schon ein Partner!' WHERE (`entry`='2000000109'); /* Hahah! $N, you make quite a partner! */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt, über den Herzen und Zungen einen Zauber zu sprechen.' WHERE (`entry`='2000000110'); /* %s begins to cast a spell over the hearts and tongues. */
UPDATE `dbscript_string` SET `content_loc3`='Die Brut von Onyxia!' WHERE (`entry`='2000000111'); /* The brood of Onyxia! */
UPDATE `dbscript_string` SET `content_loc3`='Okay, Leute. Macht euch an die Arbeit und bringt diese Knochen an.' WHERE (`entry`='2000000112'); /* Okay, crew. Get to work on getting these bones installed. */
UPDATE `dbscript_string` SET `content_loc3`='Ich brauche nur wenige Minuten, um das Serum zuzubereiten, $n.' WHERE (`entry`='2000000113'); /* The serum will only take a few minutes to prepare, $N. */
UPDATE `dbscript_string` SET `content_loc3`='Fast fertig...' WHERE (`entry`='2000000114'); /* Almost done... */
UPDATE `dbscript_string` SET `content_loc3`='Endlich ist das Serum vollendet, $n. Kommt jetzt näher. Wir müssen reden.' WHERE (`entry`='2000000115'); /* At last, the serum is complete, $N. Now, come closer. We must talk. */
UPDATE `dbscript_string` SET `content_loc3`='%s trinkt einen großen Schluck Bier.' WHERE (`entry`='2000000116'); /* %s takes big swig of ale. */
UPDATE `dbscript_string` SET `content_loc3`='Das war erfrischend. Jetzt zu den Informationen, die ich loswerden muss...' WHERE (`entry`='2000000117'); /* That was refreshing. Now there\'s information that needs to be told... */
UPDATE `dbscript_string` SET `content_loc3`='Ich denke, dass die Verlassenen die Verbündeten der Horde in die Irre führen... wartet... Ich fühle mich so... benommen...' WHERE (`entry`='2000000118'); /* I believe the Forsaken are misleading the allies of the Horde... wait... I feel so... dizzy... */
UPDATE `dbscript_string` SET `content_loc3`='%s windet sich vor Schmerzen.' WHERE (`entry`='2000000119'); /* %s writhes in pain. */
UPDATE `dbscript_string` SET `content_loc3`='AAAAAAAARGH!' WHERE (`entry`='2000000120'); /* AAAAAAAAAAAAAAAARGH */
UPDATE `dbscript_string` SET `content_loc3`='Hiermit zerstöre ich diese Instrumente des Bösen! Für die Horde!' WHERE (`entry`='2000000121'); /* I hereby destroy these instruments of evil! For the Horde! */
UPDATE `dbscript_string` SET `content_loc3`='Bitte folgt mir.' WHERE (`entry`='2000000122'); /* Please, follow me. */
UPDATE `dbscript_string` SET `content_loc3`='Ich habe noch nicht herausgefunden, was es genau ist, aber irgendetwas an den heißen Quellen ist seltsam...' WHERE (`entry`='2000000123'); /* I haven\'t really figured out what it is, but there\'s something strange about the hot springs... */
UPDATE `dbscript_string` SET `content_loc3`='%s wirft das Schwert in den seichten Teich.' WHERE (`entry`='2000000124'); /* %s tosses the sword into the shallow pool. */
UPDATE `dbscript_string` SET `content_loc3`='Ich habe etwas festgestellt. Immer, wenn ich etwas in dieses Wasser werfe, dann hat es sich geradezu unvorstellbar zu seinem Vorteil verändert, wenn ich es wieder heraushole.' WHERE (`entry`='2000000125'); /* I\'ve found that when I throw something into this water, it has improved incredibly when I retrieve it. */
UPDATE `dbscript_string` SET `content_loc3`='Na, was auch immer der Grund dafür sein mag, es funktioniert jedenfalls wunderbar!' WHERE (`entry`='2000000126'); /* Well, whatever it is, it works quite well! */
UPDATE `dbscript_string` SET `content_loc3`='Und ich bin fest entschlossen, mehr herauszufinden... Solltet Ihr also meine Hilfe wieder benötigen, dann wisst Ihr ja, wo Ihr mich finden könnt.' WHERE (`entry`='2000000127'); /* And I am determined to find out more... So if you need my help again, you know where I\'ll be. */
UPDATE `dbscript_string` SET `content_loc3`='Ehret Eure Helden! Heute haben sie einem unserer verhasstesten Feinde einen schweren Schlag beigebracht! Rend Schwarzfaust, der falsche Kriegshäuptling, ist gefallen!' WHERE (`entry`='2000000128'); /* Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen! */
UPDATE `dbscript_string` SET `content_loc3`='Badet in meiner Macht! Trinkt meine Kraft! Kämpft zum Ruhm der Horde!' WHERE (`entry`='2000000129'); /* Be bathed in my power! Drink in my might! Battle for the glory of the Horde! */
UPDATE `dbscript_string` SET `content_loc3`='Diese Urkunden gehören mir, Bruder! Bald schon werdet Ihr mir nicht mehr im Wege stehen!' WHERE (`entry`='2000000130'); /* The deeds are mine, brother! Soon you shall be out of my way for good! */
UPDATE `dbscript_string` SET `content_loc3`='Oh Mann, ich dachte wirklich, dass das mein sicheres Ende gewesen sei. Ugh... bin noch ganz benommen...' WHERE (`entry`='2000000131'); /* Oh man, I thought I was dead for sure. Ugh... still dizzy... */
UPDATE `dbscript_string` SET `content_loc3`='Ich denke, ich komme alleine zur Festung zurück. Jetzt, da Ihr mir Zeit verschafft habt, dürfte ich mich herausschleichen können. Wer immer Ihr auch sein mögt...danke. Möge Elune Euch stets segnen!' WHERE (`entry`='2000000132'); /* I can get back to the Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always! */
UPDATE `dbscript_string` SET `content_loc3`='Das dürfte nicht lange dauern...' WHERE (`entry`='2000000133'); /* This shouldn\'t take long... */
UPDATE `dbscript_string` SET `content_loc3`='Der Unsichtbarkeitsschnaps steht für Euch bereit, $n.' WHERE (`entry`='2000000134'); /* The invisibility liquor is ready for you, $n */
UPDATE `dbscript_string` SET `content_loc3`='Das geht runter wie Nichts...' WHERE (`entry`='2000000135'); /* Here goes nothing... */
UPDATE `dbscript_string` SET `content_loc3`='Corbett, mein Teurer. Harlan benötigt so schnell wir können eine Ladung gestrickter Hemden und Hosen.' WHERE (`entry`='2000000139'); /* Corbett, dear. Harlan needs a load of knitted shirts and pants as soon as we can manage. */
UPDATE `dbscript_string` SET `content_loc3`='Corbett, seid Ihr da? Harlan benötigt noch eine Ladung Strickwaren. Könnt Ihr sie ihm bringen?' WHERE (`entry`='2000000140'); /* Corbett, you there? Harlan needs another load of knitted goods. Can you take it to him? */
UPDATE `dbscript_string` SET `content_loc3`='Es war mir ein Vergnügen, Zuckerschnute. Ich bin bald zurück...' WHERE (`entry`='2000000141'); /* My pleasure, sugar drop. I\'ll be back soon... */
UPDATE `dbscript_string` SET `content_loc3`='Die Geschäfte im Basar scheinen ja gut zu laufen. Ich werde ihm sofort Nachschub bringen!' WHERE (`entry`='2000000142'); /* Business must be good down at the bazaar. I\'ll get him resupplied right away! */
UPDATE `dbscript_string` SET `content_loc3`='Hm... wenn ich das hier losgeworden bin, werde ich vielleicht in dieses Käsegeschäft gehen und mir dort einen kleinen Imbiss genehmigen.' WHERE (`entry`='000000143'); /* Hm... after dropping this off, I think I\'ll head to that cheese shop for a snack. */
UPDATE `dbscript_string` SET `content_loc3`='Ich müsste doch ein paar Münzen bei diesem Geschäft verdient haben. Vielleicht kaufe ich mir ein Mittagessen...' WHERE (`entry`='2000000144'); /* I should have a few extra coins from this sale. Maybe I\'ll buy myself some lunch... */
UPDATE `dbscript_string` SET `content_loc3`='He, Harlan. Hier ist eine Ladung Strickstoff für Euch.' WHERE (`entry`='2000000145'); /* Hey Harlan. Here\'s a load of knitted cloth for you. */
UPDATE `dbscript_string` SET `content_loc3`='Uff! Hier ist eine neue Ladung an Vorräten, Harlan. Euer Geschäft scheint ja gut zu laufen!' WHERE (`entry`='2000000146'); /* Oomph! Here\'s a load of supplies. It must be selling fast! */
UPDATE `dbscript_string` SET `content_loc3`='Ah ja, und pünktlich geliefert. Es ist wie immer ein Vergnügen, mit Euch Geschäfte zu machen, Corbett.' WHERE (`entry`='2000000147'); /* Ah yes, and promptly delivered. As always, it\'s a pleasure doing business with you, Corbett. */
UPDATE `dbscript_string` SET `content_loc3`='Ah, das weiß ich sehr zu schätzen, Corbett. Wir werden alles sofort in die Regale räumen.' WHERE (`entry`='2000000148'); /* Ahh, much appreciated, Corbett. We\'ll get these on the racks immediately. */
UPDATE `dbscript_string` SET `content_loc3`='Schön zu sehen, dass es Euch so gut geht, Harlan. Und ich hoffe, wir sehen uns bald wieder...' WHERE (`entry`='2000000149'); /* Glad to see you\'re doing so well, Harlan. And I hope to see you again soon? */
UPDATE `dbscript_string` SET `content_loc3`='Dann will ich mal wieder. Macht\'s gut, Harlan.' WHERE (`entry`='2000000150'); /* Well, I am off than. Take care, Harlan! */
UPDATE `dbscript_string` SET `content_loc3`='Nun zu diesem Imbiss...' WHERE  (`entry`='2000000151'); /* content: Now for that snack... */
UPDATE `dbscript_string` SET `content_loc3`='Hallo, Triasklan! Eine Kugel von Eurem geräucherten Mozzarella, bitte!' WHERE (`entry`='2000000152'); /* Hullo, Trias clan! A ball of your smoked mozzarella, if you please! */
UPDATE `dbscript_string` SET `content_loc3`='Guten Tag, Elling! Hallo Elaine! Kann ich einen Laib Blaukäse bekommen?' WHERE (`entry`='2000000153'); /* Good day. Elling! Hullo Elaine! Let me have a wheel of blue cheese, eh? */
UPDATE `dbscript_string` SET `content_loc3`='Guten Tag, Corbett. Hier ist Euer Käse. Heute Morgen ganz frisch gemacht! Und wie läuft Euer Laden?' WHERE (`entry`='2000000154'); /* Good day, Corbett. Here\'s your cheese, fresh made this morning! And how are things at your shop? */
UPDATE `dbscript_string` SET `content_loc3`='Hallo, Corbett! Bitte sehr! Sehe ich es richtig, dass Euer Tuchladen gut läuft...?' WHERE (`entry`='2000000155'); /* Hi Corbett! Here, you go! I trust business is faring well at your clothier shop...? */
UPDATE `dbscript_string` SET `content_loc3`='Ja, gnädige Frau, das Geschäft läuft gut!' WHERE (`entry`='2000000156'); /* Yes ma\'am, business is brisk! */
UPDATE `dbscript_string` SET `content_loc3`='Danke für den Käse!' WHERE (`entry`='2000000157'); /* Thanks for the cheese! */
UPDATE `dbscript_string` SET `content_loc3`='Zeit, wieder zurück in den Laden zu gehen...' WHERE (`entry`='2000000158'); /* Time to get back to the shop... */
UPDATE `dbscript_string` SET `content_loc3`='Ich bin zurück!' WHERE (`entry`='2000000159'); /* I\'m back! */
UPDATE `dbscript_string` SET `content_loc3`='Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE (`entry`='2000000160'); /* Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul */
UPDATE `dbscript_string` SET `content_loc3`='Aaarrrrr!!' WHERE (`entry`='2000000161'); /* ROARRRRR!! */
UPDATE `dbscript_string` SET `content_loc3`='DUNKELHAIN... ICH HUNGER!!' WHERE (`entry`='2000000162'); /* DARKSHIRE... I HUNGER!! */
UPDATE `dbscript_string` SET `content_loc3`='Wildherzen Euch töten, wenn Ihr zurück kommt. Ihr hier nicht mehr willkommen!' WHERE (`entry`='2000000163'); /* I said GOOD DAY! */
UPDATE `dbscript_string` SET `content_loc3`='Mein Schwert Archeus hat mir in meinem Leben gut gedient. Aber nun, da mein Geist mein glückloses Dasein verlässt, brauche ich es nicht länger.' WHERE (`entry`='2000000164'); /* My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer. */
UPDATE `dbscript_string` SET `content_loc3`='Ich werde mich an die Liebe meiner Tochter klammern und hoffen, dass mir im Licht meine Sünden vergeben werden.' WHERE (`entry`='2000000165'); /* I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins. */
UPDATE `dbscript_string` SET `content_loc3`='OH NEIN! Der König is tot! Eh... lang lebe der neue König! Jo!' WHERE (`entry`='2000000166'); /* OH NOES! Da king is dead! Uh... hail to da new king! Yeah! */
UPDATE `dbscript_string` SET `content_loc3`='Yar, er ist jetzt tot. Das macht Euch den neue König... äh, Euch alle! Gordok gehören jetzt Euch, Boss! Wenn Ihr lernen wollt, was König alles machen kann, fragen mich. Ich war... Berater! Jaha, darum mich alle nennen der Gewiefte!' WHERE (`entry`='2000000167'); /* Yar, he\'s dead all right. That makes you da new king... well, all of you! Gordok is yours now, boss! You should talk to me so you can learn everything there is about being da king! I was... is his assistant! Yeah, that\'s why I\'m called da crafty one! */
UPDATE `dbscript_string` SET `content_loc3`='%s starrt nach Nordwesten und lässt ein langes, herausgezogenes Heulen von sich.' WHERE (`entry`='2000000168'); /* %s stares to the northwest and lets out a long, drawn out howl. */
UPDATE `dbscript_string` SET `content_loc3`='%s lässt ein mächtiges Heulen von sich.' WHERE (`entry`='2000000169'); /* %s lets forth a mighty howl. */
UPDATE `dbscript_string` SET `content_loc3`='Wie Ihr befehlt!' WHERE (`entry`='2000000170'); /* By your command */
UPDATE `dbscript_string` SET `content_loc3`='Wartet hier, $n. Der Spionagebot wird Lescovar schnellstens herauslocken. Seid bereit! Greift erst an, wenn Ihr das Gespräch mitgehört habt.' WHERE (`entry`='2000000171'); /* Wait here, $N. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you\'ve overheard their conversation. */
UPDATE `dbscript_string` SET `content_loc3`='Einen guten Tag Euch beiden. Ich möchte Lord Lescovar sprechen.' WHERE (`entry`='2000000172'); /* Good day to you both. I would speak to Lord Lescovar */
UPDATE `dbscript_string` SET `content_loc3`='Natürlich. Er erwartet Euch in der Bibliothek.' WHERE (`entry`='2000000173'); /* Of course. He awaits you in the library */
UPDATE `dbscript_string` SET `content_loc3`='Danke. Das Licht sei mit Euch beiden.' WHERE (`entry`='2000000174'); /* Thank you. The Light be with you both. */
UPDATE `dbscript_string` SET `content_loc3`='Mylord, Euer Gast ist da. Er erwartet Euch.' WHERE (`entry`='2000000175'); /* Milord, your guest has arrived. He awaits your presence. */
UPDATE `dbscript_string` SET `content_loc3`='Ah, vielen Dank. Bleibt hier in der Bibliothek, während ich mich um diese kleine Angelegenheit kümmere.' WHERE (`entry`='2000000176'); /* Ah, thank you kindly. I will leave you to the library while I tend to this small matter. */
UPDATE `dbscript_string` SET `content_loc3`='Ich werde die Zeit zu nutzen wissen, Mylord. Danke.' WHERE (`entry`='2000000177'); /* I shall use this time wisely, milord. Thank you. */
UPDATE `dbscript_string` SET `content_loc3`='Es ist Zeit für meine Meditation, lasst mich allein.' WHERE (`entry`='2000000178'); /* It\'s time for my meditation, leave me. */
UPDATE `dbscript_string` SET `content_loc3`='Ja, Sire!' WHERE (`entry`='2000000179'); /* Yes, sir! */
UPDATE `dbscript_string` SET `content_loc3`='%s wartet, bis die Wachen außer Sichtweite sind.' WHERE (`entry`='2000000180'); /* %s waits for the guards to be out of sight. */
UPDATE `dbscript_string` SET `content_loc3`='Da seid Ihr ja. Was gibt es für Neuigkeiten aus Westfall?' WHERE (`entry`='2000000181'); /* There you are. What news from Westfall? */
UPDATE `dbscript_string` SET `content_loc3`='Van Cleef lässt mitteilen, dass die Pläne unterwegs seien. Doch er hat Gerüchte vernommen, dass irgendjemand herumschnüffelt.' WHERE (`entry`='2000000182'); /* VanCleef sends word that the plans are underway. But he\'s heard rumors about someone snooping about. */
UPDATE `dbscript_string` SET `content_loc3`='Hmm, das könnte dieser Schnüffler Shaw sein. Ich werde sehen, was ich herausfinden kann. Und nun fort mit Euch. Ich werde Euch bald wieder aufsuchen.' WHERE (`entry`='2000000183'); /* Hmm, it could be that meddler Shaw. I will see what I can discover. Be off with you. I\'ll contact you again soon. */
UPDATE `dbscript_string` SET `content_loc3`='Wohlan denn. Dann werde ich zurückkehren.' WHERE (`entry`='2000000184'); /* Very well. I will return then. */
UPDATE `dbscript_string` SET `content_loc3`='Das ist es! Darauf habt Ihr gewartet! TÖTET SIE!' WHERE (`entry`='2000000185'); /* That\'s it! That\'s what you were waiting for! KILL THEM! */
UPDATE `dbscript_string` SET `content_loc3`='Verteidigt euch, Dummkopf!' WHERE (`entry`='2000000186'); /* Defend yourself, fool! */
UPDATE `dbscript_string` SET `content_loc3`='Die Monstrosität ist in das Lager der Nachtwache eingefallen! Schnell, wir müssen sie abfangen, bevor sie die Stadt erreicht!' WHERE (`entry`='2000000187'); /* The abomination has overrun the Night Watch camp! Quickly, we must intercept it before it reaches town! */
UPDATE `dbscript_string` SET `content_loc3`='Die Bestie wurde erschlagen! Jetzt herrscht wieder Ruhe in Dunkelhain!' WHERE (`entry`='2000000188'); /* The beast is slain! All is well in Darkshire. */
UPDATE `dbscript_string` SET `content_loc3`='Stacheleberfetzen! Die dürften den Zweck erfüllen. Fische lieben Stacheleber.' WHERE (`entry`='2000000189'); /* Quillboar scraps! These should do the trick. Fish love Quillboar. */
UPDATE `dbscript_string` SET `content_loc3`='Hab einen gefangen! Werde mal sehen, ob eine der Wachen hungrig ist. Komm mit Reißzahn!' WHERE (`entry`='2000000190'); /* Caught one! I\'ll see if any of the guards are hungry. Come on Fang! */
UPDATE `dbscript_string` SET `content_loc3`='Falls Ihr hungrig sein solltet, ich habe einen Fisch gefangen...' WHERE (`entry`='2000000191'); /* I caught a fish if you are hungry... */
UPDATE `dbscript_string` SET `content_loc3`='Das nenne ich einen guten Fang! Ihr ehrt die Horde, Junge, wir danken dir!' WHERE (`entry`='2000000192'); /* A nice catch it is at that! You bring honor to the Horde boy, We thank you! */
UPDATE `dbscript_string` SET `content_loc3`='Wie Ihr wünscht...' WHERE (`entry`='2000000195'); /* As you wish... */
UPDATE `dbscript_string` SET `content_loc3`='Ich bezweifle stark, dass er irgendwas dazu zu sagen hat, Fremder...' WHERE (`entry`='2000000196'); /* I very much doubt that he will have anything to say, stranger... */
UPDATE `dbscript_string` SET `content_loc3`='Ich persönlich hatte kein Problem mit ihm. Es war der Prinz, der an ihm als Hochelf ein Exempel statuieren ließ. Leider bin ich nicht derjenige, der den Prinzen in Frage stellen kann. Zur seiner Verteidigung muss ich noch anmerken, dass er Meister Winthalus nicht sofort einäschern ließ.' WHERE (`entry`='2000000197'); /* 'I personally didn\'t mind him. It was the Prince who took exception to a high elf in his domain. Alas, I am not one to question the Prince. In his defense, he did not incinerate Master Winthalus immediately. */
UPDATE `dbscript_string` SET `content_loc3`='Wir möchten nicht, dass noch irgendjemand auf uns aufmerksam wird, Fremder. Kehrt zu denen zurück, die Euch hierher geschickt haben, und sagt ihnen, dass Ihr nichts finden konntet. Wenn Ihr das getan habt (und ich werde erfahren, ob Ihr meinen Rat befolgt habt), kehrt zu mir zurück, und ich werde Euch über das Schicksal der Verstorbenen aufklären.' WHERE (`entry`='2000000198'); /* We most definitely do not need any more attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased. */
UPDATE `dbscript_string` SET `content_loc3`='Hmmm... wo ist mein Angelhaken? Oh, da ist er ja.' WHERE (`entry`='2000000199'); /* Hmmm.... Where is my fishing hook? Oh, there it is. */
UPDATE `dbscript_string` SET `content_loc3`='Mal sehen, ob die Fische anbeißen.' WHERE (`entry`='2000000200'); /* Let\'s see if the fish are biting. */
UPDATE `dbscript_string` SET `content_loc3`='Hmmm... ich glaube ich brauche einen besseren Köder. Ich werde mal im Wagen meines Vaters nachsehen.' WHERE (`entry`='2000000201'); /* Hmmm... I think I need better bait. I\'ll check my father\'s wagon. */
UPDATE `dbscript_string` SET `content_loc3`='Was? $n, Ihr habt mir gut gedient, aber...' WHERE (`entry`='2000000234'); /* What? $N, you served me well, but... */
UPDATE `dbscript_string` SET `content_loc3`='Warum habt Ihr mich so früh beschworen? Ich habe meine volle Macht noch nicht erreicht!' WHERE (`entry`='2000000235'); /* Why have you summoned me so soon? I haven\'t yet reached my full power! */
UPDATE `dbscript_string` SET `content_loc3`='Einerlei. Ihr wart dumm genug, mir zu helfen, und jetzt werdet Ihr dafür bezahlen!' WHERE (`entry`='2000000236'); /* No matter. You were a fool to help me, and now you will pay! */
UPDATE `dbscript_string` SET `content_loc3`='Nochmals danke, $n. Ich werde jetzt einfach hier warten, bis ich ungefährdet gehen kann.' WHERE (`entry`='2000000237'); /* Thank again, $n.  Now I\'ll just wait here until it\'s safe to leave. */
UPDATE `dbscript_string` SET `content_loc3`='Die Anzahl meiner Gefährten schwindet, Göttin, und meine eigene Macht wird bald nicht mehr ausreichen, die Dämonen des Teufelswaldes zurückzuhalten.' WHERE (`entry`='2000000238'); /* The numbers of my companions dwindles, goddess, and my own power shall soon be insufficient to hold back the demons of Felwood. */
UPDATE `dbscript_string` SET `content_loc3`='Göttin, gewähre mir die Stärke, meine Feinde zu besiegen! Hör mich bitte an, ich bin verzweifelt in meiner Not und meine Sache ist gerecht!' WHERE (`entry`='2000000239'); /* Goddess, grant me the power to overcome my enemies! Hear me, please, my need is desperate and my cause is just! */
UPDATE `dbscript_string` SET `content_loc3`='Was... was ist das? Könnte das die Antwort auf meine Gebete sein? Elune hat mir eine Waffe gewährt - diese Sense -, um die Dämonen zu besiegen.' WHERE (`entry`='2000000240'); /* What... what is this? Could this by the answer to my prayers? Elune has granted me a weapon -- this scythe -- to defeat the demons. */
UPDATE `dbscript_string` SET `content_loc3`='Ich habe versagt... Ich habe in meiner Pflicht versagt... habe mein Volk enttäuscht... Die Worgs sind wild und die Sense meiner Göttin ist verloren.' WHERE (`entry`='2000000241'); /* I have failed... I have failed in my duty... failed my people... The worgen run rampant, and the Scythe of my goddess is lost. */
UPDATE `dbscript_string` SET `content_loc3`='Das Böse, das ich entfesselt habe... In wessen Hand mag die Stärke, die meine Göttin mir gewährte, nun liegen?... Wessen Hand führt sie nun?' WHERE (`entry`='2000000242'); /* This evil I have unleashed... In whose hand does the power my goddess granted to me now lie... By whose hand is it directed? */
UPDATE `dbscript_string` SET `content_loc3`='Terenthis, Raene schickte mich, um Euch zu suchen. Die Schildwachen des Eschentals brauchen Hilfe.' WHERE (`entry`='2000000260'); /* Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale. */
UPDATE `dbscript_string` SET `content_loc3`='Die Macht der Träne der Monde gehört jetzt mir! Mir ganz allein!' WHERE (`entry`='2000000345'); /* The power of the Tear of the Moons is mine! Mine I say! */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt, die Träne der Monde zu reiben.' WHERE (`entry`='2000000346'); /* %s begins to rub the Tear of the Moons. */
UPDATE `dbscript_string` SET `content_loc3`='Macht! Glorreiche Macht!' WHERE (`entry`='2000000347'); /* Power! Glorious power! */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt, seltsame Grunzgeräusche von sich zu geben. Die Träne der Monde fällt zu Boden und zerspringt.' WHERE (`entry`='2000000348'); /* %s begins to make strange grunting noises. The Tear of the Moons drops to the ground and shatters. */
UPDATE `dbscript_string` SET `content_loc3`='Spendet den Wohltätigkeitsorganisationen, die den Opfern dieser schweren Zeit zu helfen versuchen! Bitte.' WHERE (`entry`='2000000349'); /* Give to the charities who seek to help the victims of these hard times! Please. */
UPDATE `dbscript_string` SET `content_loc3`='Vergesst nicht die Waisen aus Sturmwind!' WHERE (`entry`='2000000350') /* Don\'t forget the orphans of Stormwind! */
UPDATE `dbscript_string` SET `content_loc3`='Gebt von Herzen und aus vollen Taschen! Gebt für die Kinder aus Sturmwind, die ihre Eltern verloren haben.' WHERE (`entry`='2000000351') /* Give of your hearts and your purses! Give to the children of Stormwind who have lost their parents. */
UPDATE `dbscript_string` SET `content_loc3`='Helft den Kindern aus Sturmwind... den Opfern des Krieges und der Seuche!' WHERE (`entry`='2000000352') /* Help the children of Stormwind... victims of the war and plague! */
UPDATE `dbscript_string` SET `content_loc3`='Kommt, $n. Der See befindet sich direkt hinter der nächsten Biegung.' WHERE (`entry`='2000000375'); /* Come,  $N. The lake is around the bend. */
UPDATE `dbscript_string` SET `content_loc3`='Bleibt in meiner Nähe, $n. Ich werde Euch beschützen, falls etwas schief geht.' WHERE (`entry`='2000000376'); /* Stand near me,  $N. I will protect you should anything go wrong. */
UPDATE `dbscript_string` SET `content_loc3`='Malfurion!' WHERE (`entry`='2000000377'); /* Malfurion! */
UPDATE `dbscript_string` SET `content_loc3`='Remulos, mein alter Freund. Es ist schön, Euch wiederzusehen. Ich wusste, dass meine Botschaft Euch erreichen würde, auf dem einen oder auf dem anderen Weg.' WHERE (`entry`='2000000378'); /* Remulos,  old friend. It is good to see you once more. I knew the message would find its way to you - one way or another. */
UPDATE `dbscript_string` SET `content_loc3`='Alles ist von schrecklichen Alpträumen durchzogen, Malfurion. Was geht im Smaragdgrünen Traum nur vor? Was könnte ihn derartig grausam verzerren?' WHERE (`entry`='2000000379'); /* It was shrouded in nightmares,  Malfurion. What is happening in the Dream? What could cause such atrocities? */
UPDATE `dbscript_string` SET `content_loc3`='Ich fürchte das Schlimmste, alter Freund. Innerhalb des Smaragdgrünen Traums bekämpfen wir einen neuen Feind, geboren aus uraltem Bösen. Yseras edle Brut ist den uralten Einflüsterungen erlegen. Es scheint, als sei es dem Alptraum gelungen die Grenzen der Traumwelt zu durchbrechen, um sich in Azeroth einen neuen Wirt zu suchen.' WHERE (`entry`='2000000380'); /* I fear for the worst,  old friend. Within the Dream we fight a new foe,  born of an ancient evil. Ysera\'s noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm to find a new host on Azeroth. */
UPDATE `dbscript_string` SET `content_loc3`='Ich habe es auch gespürt, Malfurion. Dunkle Zeiten werfen ihre Schatten voraus.' WHERE (`entry`='2000000381'); /* I sensed as much,  Malfurion. Dark days loom ahead. */
UPDATE `dbscript_string` SET `content_loc3`='Ja, Remulos. Die sterblichen Völker müssen auf das Kommende vorbereitet werden.' WHERE (`entry`='2000000382'); /* Aye Remulos,  prepare the mortal races. */
UPDATE `dbscript_string` SET `content_loc3`='Ihr seid schon zu lange fort, Malfurion. Der Frieden zwischen den Kindern Azeroths ist bestenfalls brüchig. Was ist mit meinem Vater? Eurem Bruder? Habt Ihr Neuigkeiten?' WHERE (`entry`='2000000383'); /* You have been gone too long,  Malfurion. Peace between the Children of Azeroth has become tenuous at best. What of my father? Of your brother? Have you any news? */
UPDATE `dbscript_string` SET `content_loc3`='Cenarius kämpft an meiner Seite. Illidan verweilt, vor sich hinbrütend, auf seinem Thron in der Scherbenwelt. Ich befürchte, dass die Niederlage gegen Arthas ihn innerlich gebrochen hat. Er scheint dem Wahnsinn anheim gefallen zu sein, Remulos. In seinen Gedanken wiederholt er immer und immer wieder die vergangenen Ereignisse, doch in Gedanken macht er alles richtig. In seinem Verstand besiegt er Arthas ein auf das andere Mal, es ist ein endloser Kreislauf. Er ist schon zu weit von uns gegangen, mein alter Freund. Ich fürchte, es naht die Zeit, in der unser Freundschaft auf die Probe gestellt wird, ganz anders als damals am Brunnen in Zin-Azshari.' WHERE (`entry`='2000000384'); /* Cenarius fights at my side. Illidan sits atop his throne in Outland - brooding. I\'m afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him,  Remulos. He replays the events in his mind a thousand times per day,  but in his mind,  he is the victor and Arthas is utterly defeated. He is too far gone,  old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari. */
UPDATE `dbscript_string` SET `content_loc3`='Remulos, ich werde zurückgezogen... Tyrande... sende ihr meine Liebe... sagt ihr, dass es mir gut geht. Sagt ihr, dass ich zurückkehren werde... Lebt wohl...' WHERE (`entry`='2000000385'); /* Remulos,  I am being drawn back... Tyrande... send her my love... Tell her I am safe... Tell her... Tell her I will return... Farewell... */
UPDATE `dbscript_string` SET `content_loc3`='Lebt wohl, alter Freund... Lebt wohl...' WHERE (`entry`='2000000386'); /* Farewell,  old friend... Farewell... */
UPDATE `dbscript_string` SET `content_loc3`='Lasst uns zum Hain zurückkehren, Sterblicher.' WHERE (`entry`='2000000387'); /* Let us return to the grove,  mortal. */
UPDATE `dbscript_string` SET `content_loc3`='Hallo, Selarin. Ich kann Euch momentan leider nicht helfen, aber vielleicht können es einige der Abenteurer hier in Auberdine...' WHERE (`entry`='2000000395'); /* Hello, Selarin. I\'m afraid I cannot help you at the moment, but perhaps some of the adventurers here in Auberdine can... */
UPDATE `dbscript_string` SET `content_loc3`='Habt Dank, Terenthis. Ich werde hier bleiben, solange ich kann.' WHERE (`entry`='2000000396'); /* Thank you, Terenthis. I shall remain here for as long as I can. */
UPDATE `dbscript_string` SET `content_loc3`='Hoffentlich kann ich eine würdige Unterstützung schicken, um dem Eschental und den Schildwachen zu helfen.' WHERE (`entry`='2000000397'); /* Hopefully I can send a worthy few to help Ashenvale and the Sentinels. */
UPDATE `dbscript_string` SET `content_loc3`='Seid bereit! Wenn die Naga erst wissen, dass wir am Leben sind, werden sie nicht zögern, ihren Vorteil zu nutzen.' WHERE (`entry`='2000000466'); /* Stand Prepared! The naga won\'t wait long to press their advantage once they know we\'re alive. */
UPDATE `dbscript_string` SET `content_loc3`='Opus möchte etwas von Cuergos Gold... mit Wurm.' WHERE (`entry`='2000005001'); /* Opus wants some Cuergo\'s Gold... with worm. */
UPDATE `dbscript_string` SET `content_loc3`='Bijou ist verloren! KRÄCHZ! *hust*' WHERE (`entry`='2000005002'); /* Bijou lost! SQUAWK! *cough */
UPDATE `dbscript_string` SET `content_loc3`='Kibler wird vom Fantasy-Tierschutz untersucht.' WHERE (`entry`='2000005003'); /* Kibler is being investigated by G.E.T.A. */
UPDATE `dbscript_string` SET `content_loc3`='Bijou weiß, wo Schätze verborgen sind.' WHERE (`entry`='2000005004'); /* Bijou knows where treasures are hidden. */
UPDATE `dbscript_string` SET `content_loc3`='Großdrachen kontrollieren Orcs!? KRÄCHZ!' WHERE (`entry`='2000005005'); /* Dragons controlling orcs!? SQUAWK! */
UPDATE `dbscript_string` SET `content_loc3`='Alle gehen zur Spitze, aber keiner kommt zurück... genau wie Bijou.' WHERE (`entry`='2000005006'); /* They all go to the Spire but none never come back... just like Bijou. */
UPDATE `dbscript_string` SET `content_loc3`='Fragt Kibler nach dem Schatz! KRÄCHZ!' WHERE (`entry`='2000005007'); /* Ask Kibler about the treasure! SQUAWK! */
UPDATE `dbscript_string` SET `content_loc3`='KRÄCHZ!!! *hust* *hust* Ich muss mit dem Rauchen aufhören!' WHERE (`entry`='2000005008'); /* SQUAWK!! *cough* *cough* I need to quit smoking! */
UPDATE `dbscript_string` SET `content_loc3`='Gut gemacht, Soldaten! Rührt euch!' WHERE (`entry`='2000005009'); /* Well done, soldiers! At ease! */
UPDATE `dbscript_string` SET `content_loc3`='Zug zug! Freut sich zu helfen!' WHERE (`entry`='2000005010'); /* Zug zug! Happy to help! */
UPDATE `dbscript_string` SET `content_loc3`='Ja auf der Stelle Mama!' WHERE (`entry`='2000005011'); /* Yes right away momma! */
UPDATE `dbscript_string` SET `content_loc3`='Ah, das muss er jetzt aber sein... nein? Pah!' WHERE (`entry`='2000005018'); /* Ah, this must be him now... no? */
UPDATE `dbscript_string` SET `content_loc3`='Die Macht des Lichkönigs wird stärker. Es ist von äußerster Wichtigkeit, dass unser Zeitplan seinem Vorhaben entspricht!' WHERE (`entry`='2000005027'); /* The Lich King\'s forces are building. It is imperative that our timetable supports his plans. */
UPDATE `dbscript_string` SET `content_loc3`='Morgen beginnen wir mit der Ausbildung unserer viel versprechenden Großdrachen, also vergesst Eure Kauknochen nicht.' WHERE (`entry`='2000005028'); /* Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys. */
UPDATE `dbscript_string` SET `content_loc3`='Selbst unser ältestes Großdrachengelege ist noch weit von der Reife entfernt, aber wir sind überzeugt, dass der Drachenschwarm bald so weit sein wird, wenn wir nur Geduld haben und unsere Studien sorgfältig fortsetzen.' WHERE (`entry`='2000005029'); /* Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready. */
UPDATE `dbscript_string` SET `content_loc3`='Ich komme aus dem Land im Süden... wo Männer leiden und Frauen wüten.' WHERE (`entry`='2000005031'); /* I come from the land down under... where women plague and men sunder. */
UPDATE `dbscript_string` SET `content_loc3`='...Und dann sagte der Taure, "33 ZENTIMETER!"' WHERE (`entry`='2000005032'); /* ...And then the tauren said, "13 INCHES!" */
UPDATE `dbscript_string` SET `content_loc3`='Er entkommt!' WHERE (`entry`='2000005035'); /* It\'s getting away! */
UPDATE `dbscript_string` SET `content_loc3`='Heulsuse! Heulsuse!' WHERE (`entry`='2000005057'); /* Crybaby! Crybaby! */
UPDATE `dbscript_string` SET `content_loc3`='Das Baby will seine Puppe!' WHERE (`entry`='2000005058'); /* Baby wants her dolly! */
UPDATE `dbscript_string` SET `content_loc3`='Ich frage mich, ob deine Puppe schwimmen kann!' WHERE (`entry`='2000005059'); /* I wonder if your dolly can swim! */
UPDATE `dbscript_string` SET `content_loc3`='Haha! Ich habe Betsy!' WHERE (`entry`='2000005060'); /* Ha ha! I have Betsy! */
UPDATE `dbscript_string` SET `content_loc3`='Gib mir meine Puppe!!!' WHERE (`entry`='2000005061'); /* I have your dolly! Nyah nyah! */
UPDATE `dbscript_string` SET `content_loc3`='Gib mir meine Puppe!!!' WHERE (`entry`='2000005062'); /* Gimmie my dolly!! */
UPDATE `dbscript_string` SET `content_loc3`='Tu Betsy nicht weh, du Widerling!' WHERE (`entry`='2000005063'); /* Don\'t hurt Betsy, you meanie! */
UPDATE `dbscript_string` SET `content_loc3`='Habt Ihr Drull schon befreit? Ich weiß nicht, wo er festgehalten wird.' WHERE (`entry`='2000005078'); /* Have you freed Drull yet? I don\'t know where he\'s being held. */
UPDATE `dbscript_string` SET `content_loc3`='Ich werde Euch nur aufhalten, aber kein rosahäutiger Mensch kann mir jetzt noch meine Freiheit nehmen!' WHERE (`entry`='2000005079'); /* I will only slow you down, but no pink-skinned humans will keep me from freedom! */
UPDATE `dbscript_string` SET `content_loc3`='Geht ohne mich voraus! Ich werde allein nach Tarrens Mühle reisen.' WHERE (`entry`='2000005082'); /* Go on ahead without me! I will make my own way to Tarren Mill. */
UPDATE `dbscript_string` SET `content_loc3`='Ah, es ist gut, von meinen Fesseln befreit zu sein! Habt Ihr Togthar schon befreit? Die Menschen haben uns nach der Gefangennahme getrennt.' WHERE (`entry`='2000005081'); /* Ah, it is good to be free of my bonds! Have you freed Tog\'thar yet? The humans split us up after our capture. */
UPDATE `dbscript_string` SET `content_loc3`='Jack und Jill meine Runzligen. Mir gehört all das Wasser um mich herum.' WHERE (`entry`='2000005103'); /* Jack and Jill my wrinkled patoot! I do all the water luggin\' \'round here. */
UPDATE `dbscript_string` SET `content_loc3`='Wo ist das Wasser, Emma? Hast du Wasser geholt, Emma? Wenn ich nicht wäre, würd\' das Pack gar nicht wissen, wie Wasser aussieht.' WHERE (`entry`='2000005104'); /* Where\'s the water, Emma? Get the water, Emma? If\'n it weren\'t fer me, that lot wouldn\'t know what water looks like. */
UPDATE `dbscript_string` SET `content_loc3`='Natürlich rede ich mit mir selbst. Das ist die einzige Möglichkeit, in dieser Stadt ein nettes Gespräch zu führen.' WHERE (`entry`='2000005105'); /* O\'ourse I\'m talking to myself. Only way to get a decent conversation in this city. */
UPDATE `dbscript_string` SET `content_loc3`='Als ob ich auf meine alten Tage nichts Besseres zu tun hätte, als Wassereimer zu schleppen.' WHERE (`entry`='2000005106'); /* As if I don\'t have better things to do in my old age than carry buckets of water. */
UPDATE `dbscript_string` SET `content_loc3`='Mir scheint\'s, als ginge ich hundert Mal am Tag den ganzen Weg zum Brunnen, um immer noch mehr Wasser zu holen. Keinen Respekt vor den Alten, ich sag\'s Euch.' WHERE (`entry`='2000005107'); /* Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya. */
UPDATE `dbscript_string` SET `content_loc3`='Déjà-vu. Für einen Moment dachte ich, ich wäre zu Hause... vor der Seuche...' WHERE (`entry`='2000005108'); /* Deja vu. For a moment I thought I was back home... before the plague... */
UPDATE `dbscript_string` SET `content_loc3`='Sie sagen er kann sich manchmal in einen Raben verwandeln.' WHERE (`entry`='2000005109'); /* They say he can turn into a raven sometimes. */
UPDATE `dbscript_string` SET `content_loc3`='Sie sagen er kann sich manchmal in einen Raben verwandeln.' WHERE (`entry`='2000005110'); /* They say he can turn into a raven sometimes. */
UPDATE `dbscript_string` SET `content_loc3`='Und dann biss ihm der Hase einfach den Kopf ab... Ich schwör\'s.' WHERE (`entry`='2000005111'); /* And then the rabbit just bit his head off... I swear. */
UPDATE `dbscript_string` SET `content_loc3`='Ich schwöre es, man hat sie tatsächlich schon gesehen. Es gibt die Pandaren wirklich!' WHERE (`entry`='2000005112'); /* I swear, people have actualy seen them. Pandaren really do exist!! */
UPDATE `dbscript_string` SET `content_loc3`='Es gibt einen Grund, warum die Augen von Orcs rot glühen! Sie trinken Blut!' WHERE (`entry`='2000005113'); /* You know why Orcs eyes glow red? It\'s because they drink blood! */
UPDATE `dbscript_string` SET `content_loc3`='Ich glaube nicht, dass es in diesen Kanälen Fische gibt.' WHERE (`entry`='2000005114'); /* I dont think there\'s any fish in these canals. */
UPDATE `dbscript_string` SET `content_loc3`='Genau so hat Lothar mit bloßen Händen sechsunddreißig Orcs getötet!' WHERE (`entry`='2000005115'); /* And that\'s how Lother killed thirty six orcs with his bare hands! */
UPDATE `dbscript_string` SET `content_loc3`='Iiieeh... das ist kein Fisch!' WHERE (`entry`='2000005116'); /* Eww... that\'s not a fish! */
UPDATE `dbscript_string` SET `content_loc3`='Ich habe Wurmstückchen auf meinen Schuhen...' WHERE (`entry`='2000005117'); /* I got worm guts on my shoes. */
UPDATE `dbscript_string` SET `content_loc3`='Ich glaube, ich sehe da was.' WHERE (`entry`='2000005118'); /* I think i see something. */
UPDATE `dbscript_string` SET `content_loc3`='Iiieeh... das ist kein Fisch!' WHERE (`entry`='2000005119'); /* Eww... that\'s not a fish! */
UPDATE `dbscript_string` SET `content_loc3`='Ich glaube, ich sehe da was.' WHERE (`entry`='2000005120'); /* I think i see something. */
UPDATE `dbscript_string` SET `content_loc3`='Ich hoffe, das war ein Fisch!' WHERE (`entry`='2000005121'); /* I hope that was a fish! */
UPDATE `dbscript_string` SET `content_loc3`='Wurm kommt an den Haken, Haken kommt ins Wasser. Fisch ist im Wasser, unser Fisch.' WHERE (`entry`='2000005122'); /* Worm goes on the hook, hook goes in the water, Fish is in the water, our fish. */
UPDATE `dbscript_string` SET `content_loc3`='Kannst du dir das vorstellen?' WHERE (`entry`='2000005123'); /* Can you imagine? */
UPDATE `dbscript_string` SET `content_loc3`='Wirklich?' WHERE (`entry`='2000005124'); /* Really? */
UPDATE `dbscript_string` SET `content_loc3`='Wow.' WHERE (`entry`='2000005125'); /* Wow. */
UPDATE `dbscript_string` SET `content_loc3`='Mein Vater sagt, das ist nur eine Geschichte.' WHERE (`entry`='2000005126'); /* My father says that\'s just a story. */
UPDATE `dbscript_string` SET `content_loc3`='Wirklich?' WHERE (`entry`='2000005127'); /* Really? */
UPDATE `dbscript_string` SET `content_loc3`='Wow.' WHERE (`entry`='2000005128'); /* Wow. */
UPDATE `dbscript_string` SET `content_loc3`='Klasse!' WHERE (`entry`='2000005129'); /* That\'s neat. */
UPDATE `dbscript_string` SET `content_loc3`='Wow.' WHERE (`entry`='2000005130'); /* Wow. */
UPDATE `dbscript_string` SET `content_loc3`='Wirklich?' WHERE (`entry`='2000005131'); /* Really? */
UPDATE `dbscript_string` SET `content_loc3`='Rührt euch, Hunde! Wir haben hier etwas zu erledigen!' WHERE (`entry`='2000005132'); /* Look alive, dogs! We got an operation to run here! */
UPDATE `dbscript_string` SET `content_loc3`='Hier haben wir die Kathedrale des Lichts, Sturmwinds Zentrum spiritueller Erleuchtung.' WHERE (`entry`='2000005134'); /* Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind. */
UPDATE `dbscript_string` SET `content_loc3`='Ja, das ist wahr. Sowohl Paladine als auch Priester üben ihre Fertigkeiten und erforschen die großen Wahrheiten hinter den Mauern der Kathedrale.' WHERE (`entry`='2000005135'); /* Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral. */
UPDATE `dbscript_string` SET `content_loc3`='Wenn ihr mir bitte folgen wollt, Kinder. Wir werden gleich die Burg sehen, in der König Varian höchstpersönlich auf seinem Thron sitzt.' WHERE (`entry`='2000005136'); /* Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne. */
UPDATE `dbscript_string` SET `content_loc3`='Hier haben wir Burg Sturmwind. Gebaut auf den Ruinen von Schloss Sturmwind, das während des ersten Großen Kriegs von der Horde zerstört wurde.' WHERE (`entry`='2000005137'); /* Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War. */
UPDATE `dbscript_string` SET `content_loc3`='Als die Horde zerschlagen wurde, kehrten die Mannen hierher zurück und begannen, diese einst so herrliche Stadt als Beweis unseres eigenen Überlebens wieder aufzubauen.' WHERE (`entry`='2000005138'); /* When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival. */
UPDATE `dbscript_string` SET `content_loc3`='Ja, gut... lasst uns jetzt zu dem Monument gehen, das den Helden der beiden Großen Kriege gewidmet ist, dem Tal der Helden. Folgt mir.' WHERE (`entry`='2000005139'); /* Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me. */
UPDATE `dbscript_string` SET `content_loc3`='Ist das nicht erstaunlich, Kinder? Jeder, der die Stadt betritt, muss die wachsamen Augen der größten Helden unseres Landes passieren.' WHERE (`entry`='2000005140'); /* Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands. */
UPDATE `dbscript_string` SET `content_loc3`='Atemberaubend. Kinder, wenn wir in der Schule zurück sind, wird jeder von euch einen mündlichen Bericht über eine dieser Legenden abgeben.' WHERE (`entry`='2000005141'); /* Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people. */
UPDATE `dbscript_string` SET `content_loc3`='Werft noch einen Blick darauf, bevor wir zum heiligen Distrikt und zur großen Kathedrale des Lichts aufbrechen.' WHERE (`entry`='2000005142'); /* Now, take another long look before we make our way to the Holy District and the great Cathedral of Light. */
UPDATE `dbscript_string` SET `content_loc3`='Wenn wir die Essenzströme umkehren, können wir vielleicht auch die Polarität ändern.' WHERE (`entry`='2000005148'); /* If we reverse the Essence flows perhaps we can alter the polarity. */
UPDATE `dbscript_string` SET `content_loc3`='Warum können wir das Feld nicht einfach verlagern, um die Abweichung im Fluxus zu kompensieren?' WHERE (`entry`='2000005149'); /* Why can\'t we just shift the array to compensate for the variance in the flux? */
UPDATE `dbscript_string` SET `content_loc3`='Die Magiefelder würden sich dann also in eine Kettenreaktion positiv aufgeladener Energien verwandeln.' WHERE (`entry`='2000005150'); /* So then the array of magics would cascade into a chain reaction of positively charged energies. */
UPDATE `dbscript_string` SET `content_loc3`='Die sich daraus ergebenden Energien können dennoch kollabieren, und dies könnte eine Energieströmung hervorrufen, die Euch eine Migräne für Wochen bescheren würde.' WHERE (`entry`='2000005151'); /* The magical wards at that sholud be supported enough by the energy flux to certain the entity. */
UPDATE `dbscript_string` SET `content_loc3`='Maginor sagt, dass Wechselströme positiver Energie in der Tat einen viel stabileren Fluss erzeugen.' WHERE (`entry`='2000005152'); /* Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow. */
UPDATE `dbscript_string` SET `content_loc3`='Das Portal würde sich leicht verlagern. Wenn Ihr zu diesem Zeitpunkt einen Bindezauberspruch sprecht, könnt Ihr es an Ort und Stelle verfestigen.' WHERE (`entry`='2000005153'); /* The portal will shift slightly, at this point if you cast a binding cantrip you will solidify it in place.. */
UPDATE `dbscript_string` SET `content_loc3`='Wenn die positiv ausgerichteten Energien mit den negativ aufgeladenen Energien kollidieren, heben sie einander nicht auf.' WHERE (`entry`='2000005154'); /* When the positively aligned energies collide with the negatively charged energies, they don\'t negate one another. */
UPDATE `dbscript_string` SET `content_loc3`='Zwölf Fokuszentren einzubringen könnte es den magischen Energien erlauben, sich stabiler zu formen, da sie die notwendige Stabilität einbringen.' WHERE (`entry`='2000005155'); /* Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability. */
UPDATE `dbscript_string` SET `content_loc3`='Ich denke nicht. Ich möchte nicht wieder hochgejagt werden.' WHERE (`entry`='2000005156'); /* I think not, I don\'t need to be blown up again. */
UPDATE `dbscript_string` SET `content_loc3`='Ich denke, dass es funktionieren könnte, wenn wir zum Zaubern zwanzig Leute zur Verfügung hätten.' WHERE (`entry`='2000005157'); /* I suppose that could work, if we had twenty people to cast it with. */
UPDATE `dbscript_string` SET `content_loc3`='Würde das nicht ein Kreuzen der Strahlen bedeuten? Ist das nicht ziemlich schlimm?' WHERE (`entry`='2000005158'); /* But wouldn\'t that mean crossing the streams? Isn\'t that really bad?? */
UPDATE `dbscript_string` SET `content_loc3`='Aber was passiert, wenn die resultierende Frequenzverschiebung eine magische Rückkopplung durch die Ströme schickt?' WHERE (`entry`='2000005159'); /* But what if the resulting frequency shift were to send magical feedback up the flows? */
UPDATE `dbscript_string` SET `content_loc3`='Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?' WHERE (`entry`='2000005160'); /* But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula? */
UPDATE `dbscript_string` SET `content_loc3`='Das wird jedoch den magischen Fokus aus der Balance bringen und im Äther eine umgekehrte Vibration verursachen.' WHERE (`entry`='2000005161'); /* That will unbalance the magical focus, though, and cause a reverse vibration in the ether. */
UPDATE `dbscript_string` SET `content_loc3`='Würde das nicht bewirken, dass die Bindung sich löst, wenn sie nicht vor Beginn des Zauberns richtig verankert wurde?' WHERE (`entry`='2000005162'); /* Wouldn\'t that cause the weave to unravel if not properly anchored before starting the casting? */
UPDATE `dbscript_string` SET `content_loc3`='Die resultierenden Energien könnten natürlich kollabieren und das könnte wiederum einen Energiefluss erzeugen, der Euch die nächsten Wochen eine Migräne bescheren würde.' WHERE (`entry`='2000005163'); /* The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks. */
UPDATE `dbscript_string` SET `content_loc3`='Zumindest wären wir dann nicht da, um sauber machen zu müssen.' WHERE (`entry`='2000005164'); /* At least we wouldn\'t be around to have to clean it up. */
UPDATE `dbscript_string` SET `content_loc3`='Hui, und das alles für einen Liebestrank. Hoffentlich ist er es wert.' WHERE (`entry`='2000005165'); /* Wow, all of this for a love potion. Hope he\'s worth it.. */
UPDATE `dbscript_string` SET `content_loc3`='Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.' WHERE (`entry`='2000005166'); /* Only if we didn\'t follow the proper initialization procedures. */
UPDATE `dbscript_string` SET `content_loc3`='Stimmt es, dass die Paladine hier trainieren?' WHERE (`entry`='2000005167'); /* Is it true that the paladins train here? */
UPDATE `dbscript_string` SET `content_loc3`='Warum müssen wir das hier überhaupt lernen?' WHERE (`entry`='2000005168'); /* Why do we have to learn this stuff anyway? */
UPDATE `dbscript_string` SET `content_loc3`='Was wäre denn, wenn wir drei Fokusse nach tyreanischem Muster einsetzten? Das sollte die Lösung sein.' WHERE (`entry`='2000005169'); /* What if we used three focuses in Tyrean pattern? That should solve it. */
UPDATE `dbscript_string` SET `content_loc3`='Seid nicht immer so negativ. Die Chancen, dass das eintritt, stehen zwischen Null und Nichts.' WHERE (`entry`='2000005170'); /* Always so negative. The chances of that happening are between zero and none. */
UPDATE `dbscript_string` SET `content_loc3`='Wenn wir die surianische Theorie benutzen, dann ja, aber nicht, wenn wir den y\'serianischen Ansatz verfolgen.' WHERE (`entry`='2000005171'); /* If we use the Surian theory, then yes, but not if we go with the Y\'serian approach. */
UPDATE `dbscript_string` SET `content_loc3`='Aber wenn wir es mit einem Ankergewinde auf angemessenem Energiefluss stabilisieren könnten, sollte es funktionieren.' WHERE (`entry`='2000005172'); /* But if we stabilize it with an anchor thread at the appropriate energy crux then it should work. */
UPDATE `dbscript_string` SET `content_loc3`='Wenn wir eine geeignete Sequenz benutzen, sollte es funktionieren. Es werden vor Beginn nur sorgfältige Studien nötig sein.' WHERE (`entry`='2000005173'); /* If we use the appropriate sequence we should be ok. Will just take some serious studying before we start. */
UPDATE `dbscript_string` SET `content_loc3`='Hallo, Charys. Meine Liste ist fertig. Könnt Ihr mir bitte all dies besorgen, besonders die letzte Zutat?' WHERE (`entry`='2000005180'); /* Hello, Charys. I have my list, could you get me all of that, especially the last ingredient. */
UPDATE `dbscript_string` SET `content_loc3`='Sicher, Paige. Seid nur freundlich.' WHERE (`entry`='2000005181'); /* Sure Paige. Just be gentle. */
UPDATE `dbscript_string` SET `content_loc3`='Danke, Charys. Komm, Paige, Süße.' WHERE (`entry`='2000005182'); /* Thanks, Charys. C\'mon Paige, sweetie. */
UPDATE `dbscript_string` SET `content_loc3`='Mami? Kann ich Patzerle streicheln?' WHERE (`entry`='2000005183'); /* Mommy? Can I pet Fizzles? */
UPDATE `dbscript_string` SET `content_loc3`='Billy sagt, Patzerle war früher mal ein großer Zauberer. Aber ihm ist ein Zauber schiefgegangen und da ist er in einen Hasen verwandelt worden.' WHERE (`entry`='2000005184'); /* Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad. */
UPDATE `dbscript_string` SET `content_loc3`='Die magischen Studien belasten Euer Gehirn? Entspannt Euch im Blauen Eremiten!' WHERE (`entry`='2000005185'); /* Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE `dbscript_string` SET `content_loc3`='Die besten Getränke von ganz Sturmwind!' WHERE (`entry`='2000005186'); /* Best drinks in Stormwind! */
UPDATE `dbscript_string` SET `content_loc3`='Auf zum Blauen Eremiten. Dort kennt jeder Euren Namen!' WHERE (`entry`='2000005187'); /* Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE `dbscript_string` SET `content_loc3`='Seid Ihr deprimiert? Kommt zum Blauen Eremiten und habt Spaß!' WHERE (`entry`='2000005188'); /* Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE `dbscript_string` SET `content_loc3`='Die besten Getränke von ganz Sturmwind!' WHERE (`entry`='2000005189'); /* Best drinks in Stormwind! */
UPDATE `dbscript_string` SET `content_loc3`='Die magischen Studien belasten Euer Gehirn? Entspannt Euch im Blauen Eremiten!' WHERE (`entry`='2000005190'); /* Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE `dbscript_string` SET `content_loc3`='Fragt mich, wenn Ihr wissen wollt, wie man im Blauen Eremiten ein Getränk umsonst bekommt!' WHERE (`entry`='2000005191'); /* Ask me how you can get a free drink at the Blue Recluse! */
UPDATE `dbscript_string` SET `content_loc3`='Auf zum Blauen Eremiten. Dort kennt jeder Euren Namen!' WHERE (`entry`='2000005192'); /* Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE `dbscript_string` SET `content_loc3`='Kostenlose Getränke im Blauen Eremiten!' WHERE (`entry`='2000005193'); /* Free drinks at the Blue Recluse! */
UPDATE `dbscript_string` SET `content_loc3`='Seid Ihr deprimiert? Kommt zum Blauen Eremiten und habt Spaß!' WHERE (`entry`='2000005194'); /* Feeling blue? Come on down to the Blue Recluse for a good time! */
UPDATE `dbscript_string` SET `content_loc3`='Die magischen Studien belasten Euer Gehirn? Entspannt Euch im Blauen Eremiten!' WHERE (`entry`='2000005195'); /* Magical studies stressing your brain? Relax at the Blue Recluse! */
UPDATE `dbscript_string` SET `content_loc3`='Die besten Getränke von ganz Sturmwind!' WHERE (`entry`='2000005196'); /* Best drinks in Stormwind! */
UPDATE `dbscript_string` SET `content_loc3`='Fragt mich, wenn Ihr wissen wollt, wie man im Blauen Eremiten ein Getränk umsonst bekommt!' WHERE (`entry`='2000005197'); /* Ask me how you can get a free drink at the Blue Recluse! */
UPDATE `dbscript_string` SET `content_loc3`='Auf zum Blauen Eremiten. Dort kennt jeder Euren Namen!' WHERE (`entry`='2000005198'); /* Head on over to the Blue Recluse. Where everybody knows your name! */
UPDATE `dbscript_string` SET `content_loc3`='Die besten Getränke von ganz Sturmwind!' WHERE (`entry`='2000005199'); /* Best drinks in Stormwind! */
UPDATE `dbscript_string` SET `content_loc3`='Was war das für ein Krach? Es klang wie Gebrüll.' WHERE (`entry`='2000005200'); /* What was that noise? It sounded like a roar. */
UPDATE `dbscript_string` SET `content_loc3`='%s brüllt Terenthis an, um seine Aufmerksamkeit zu erregen.' WHERE (`entry`='2000005201'); /* %s roars at Terenthis to get his attention. */
UPDATE `dbscript_string` SET `content_loc3`='Grimmklaue?! Ganz ruhig, mein Freund... wo ist Euer Meister Volcor?' WHERE (`entry`='2000005202'); /* Grimclaw? Easy there, my friend... where is your master Volcor? */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt in Terenthis\' Richtung zu heulen und zu brüllen, und stampft mit seinen Pfoten auf den Boden.' WHERE (`entry`='2000005203'); /* %s begins to moan and roar at Terenthis while stomping his paws on the ground. */
UPDATE `dbscript_string` SET `content_loc3`='Hoh, hoh, mein Freund. Einen Moment...' WHERE (`entry`='2000005204'); /* Whoa, whoa there, my friend. One moment... */
UPDATE `dbscript_string` SET `content_loc3`='%s beginnt, einen Zauber auf Grimmklaue zu wirken.' WHERE (`entry`='2000005205'); /* %s begins to cast a spell on Grimclaw. */
UPDATE `dbscript_string` SET `content_loc3`='So... das sollte helfen. Jetzt sagt mir, was geschehen ist, Grimmklaue.' WHERE (`entry`='2000005206'); /* There... that should help. Now, tell me what\'s happened, Grimclaw. */
UPDATE `dbscript_string` SET `content_loc3`='%s brüllt Terenthis weiterhin an, doch dieses Mal scheint der Druide den Bären zu verstehen.' WHERE (`entry`='2000005207'); /* %s roars at Terenthis more, but this time the druid seems to understand the bear. */
UPDATE `dbscript_string` SET `content_loc3`='Ich verstehe, mein Freund. Ich werde jemanden finden, der Eurem Meister helfen kann. Geht jetzt zu ihm zurück oder bleibt wenigstens in seiner Nähe.' WHERE (`entry`='2000005208'); /* I understand, my friend. I shall find someone to help your master. Go back to him now, or at least stay close. */
UPDATE `dbscript_string` SET `content_loc3`='%s brüllt dankbar in Terenthis\' Richtung.' WHERE (`entry`='2000005209'); /* %s roars in acknowledgement at Terenthis. */
UPDATE `dbscript_string` SET `content_loc3`='Grimmklaue und sein Meister Volcor könnten Eure Hilfe gebrauchen, wenn Ihr die Zeit erübrigen könnt. Sprecht mit mir, falls Ihr Interesse habt...' WHERE (`entry`='2000005210'); /* If you have the time, Grimclaw and his master Volcor could use your help. If you\'re interested, speak with me further... */