SET NAMES 'utf8';

UPDATE `dbscript_string` SET `content_default`='Danke, $N Und viel Glück!' WHERE (`entry`='2000000000'); /* content: Thank you, $N. And luck to you. */
UPDATE `dbscript_string` SET `content_default`='Die Klippenquellfälle befinden sich in den Bergen Richtung Osten und Norden.' WHERE (`entry`='2000000001'); /* Cliffspring Falls lies along the mountains to the east and north. */
UPDATE `dbscript_string` SET `content_default`='Geht rasch, $N Mein Schicksal liegt in Eurer Hand.' WHERE (`entry`='2000000002'); /* Go swiftly $N. My fate is in your hands. */
UPDATE `dbscript_string` SET `content_default`='Großmutter Falkenwind deutet auf die Wasserkanne, die auf dem Rand des Brunnens steht.' WHERE (`entry`='2000000003'); /* %s gestures to the pitcher of water sitting on the edge of the well. */
UPDATE `dbscript_string` SET `content_default`='Es ist lange her, Bethor, mein Freund.' WHERE (`entry`='2000000004'); /* It has been a long time, Bethor, my friend. */
UPDATE `dbscript_string` SET `content_default`='Wenn es die Zeit erlaubt, dann müssen wir uns in Ruhe unterhalten, denn wir haben viel zu besprechen.' WHERE (`entry`='2000000005'); /* When time permits, we must speak at length. For we have much to discuss. */
UPDATE `dbscript_string` SET `content_default`='Und danke, $N Ohne Eure Hilfe hätte ich den Weg zu den Verlassenen nie gefunden.' WHERE (`entry`='2000000006'); /* And thank you, $N.  Without your aid I may never have found my way to the Forsaken. */
UPDATE `dbscript_string` SET `content_default`='Lebt wohl, mein Freund.' WHERE (`entry`='2000000007'); /* Farewell, my friend. */
UPDATE `dbscript_string` SET `content_default`='%s schnuppert an dem Elixier und langt dann eifrig zu!' WHERE (`entry`='2000000008'); /* %s sniffs the elixir then eagerly digs in! */
UPDATE `dbscript_string` SET `content_default`='Ah, das ist genau richtig! Ich glaube, ich hole mir noch ein paar... könnt Ihr für mich auf diese Fässer aufpassen, $N' WHERE (`entry`='2000000012'); /* Ah, that sure does hit the spot! I think i\'ll get myself a couple more...can you watch these barrels for me, $N? */
UPDATE `dbscript_string` SET `content_default`='Und wie läuft das Fassbewachen...?' WHERE (`entry`='2000000013'); /* How goes the barrel watching...? */
UPDATE `dbscript_string` SET `content_default`='Nun ja, ich muss mich wieder um die Arbeit kümmern. Aber so eine kleine Pause tut schon gut und so ein Donnerbräu Lager schmeckt immer!' WHERE (`entry`='2000000014'); /* Well, back to business for me. But it sure was nice taking that short break, and it\'s always nice drinking Thunder Ale! */
UPDATE `dbscript_string` SET `content_default`='Ich danke Euch, $n. Und mein Bruder dankt Euch ebenfalls.' WHERE (`entry`='2000000016'); /* I thank you. $n. And my brother thanks you. */
UPDATE `dbscript_string` SET `content_default`='%s beginnt zu singen, während er die Quellsteine und das Bernsteinkorn vor dem Stammesfeuer vermischt.' WHERE (`entry`='2000000017'); /* %s begins chanting as he mixes the well stones and ambercom before the Tribal Fire. */
UPDATE `dbscript_string` SET `content_default`='Das Wasser der Seher steht für Euch zum Trinken bereit, $N' WHERE (`entry`='2000000018'); /* The Water of the Seers is ready for your consumption, $N. */
UPDATE `dbscript_string` SET `content_default`='Habt Geduld, $N. Die Fackel ist fast fertig.' WHERE (`entry`='2000000019'); /* Be patient $N. The torch is almost complete. */
UPDATE `dbscript_string` SET `content_default`='Das ist interessant...' WHERE (`entry`='2000000020'); /* That\'s interesting... */
UPDATE `dbscript_string` SET `content_default`='Ich muss Noram und Horatio kontaktieren.' WHERE (`entry`='2000000021'); /* I need to consult Noram and Horatio. */
UPDATE `dbscript_string` SET `content_default`='Geht jetzt, $N. Findet Volcor... und denkt daran, dass die Magie, die Euch beschützt, versagen wird, wenn Ihr mit anderen mehr tut als bloß zu reden.' WHERE (`entry`='2000000022'); /* Go now, $N. Find Volcor... and remember, the magics protecting you will fail if you interact with anyone, save for talking. */
UPDATE `dbscript_string` SET `content_default`='%s beginnt, einen Zauber zu wirken, als Ihr ihm den Umhang abnehmt.' WHERE (`entry`='2000000023'); /* %s begins to cast a spell as you take the cloak from him. */
UPDATE `dbscript_string` SET `content_default`='M... m... mir... geht... es... nicht... gut...' WHERE (`entry`='2000000024'); /* %s I. . .I. . .don\'t. . .feel. . .right. . . */
UPDATE `dbscript_string` SET `content_default`='Mein Verstand... mein Fleisch... ich... verwese...!' WHERE (`entry`='2000000025'); /* My mind. . .my flesh. . .I\'m. . .rotting. . . .! */
UPDATE `dbscript_string` SET `content_default`='Ups!' WHERE (`entry`='2000000026'); /* Whoops! */
UPDATE `dbscript_string` SET `content_default`='Das Volk von Westfall salutiert vor $N, einem mutigen und tapferen Verteidiger der Freiheit.' WHERE (`entry`='2000000028'); /* The People of Westfall salute $N, a brave and valiant defender of freedom. */
UPDATE `dbscript_string` SET `content_default`='Das macht Sinn!' WHERE (`entry`='2000000030'); /* This makes sense! */
UPDATE `dbscript_string` SET `content_default`='Vorsicht, $n! Schaut nach Westen!' WHERE (`entry`='2000000031'); /* Beware, $n! Look to the west! */
UPDATE `dbscript_string` SET `content_default`='Seid gewappnet, $N, denn der Dämon in dieser Kugel ist eine Teufelsbestie.' WHERE (`entry`='2000000032'); /* Gird yourself $N, for the demon in this orb is a fel beast. */
UPDATE `dbscript_string` SET `content_default`='%s beschwört einen Boten...' WHERE (`entry`='2000000033'); /* %s summons a messenger... */
UPDATE `dbscript_string` SET `content_default`='Lass mich dir dabei helfen.' WHERE (`entry`='2000000034'); /* Let me help you with those. */
UPDATE `dbscript_string` SET `content_default`='Trink das, es wird dir helfen' WHERE (`entry`='2000000035'); /* Drink this, it will help. */
UPDATE `dbscript_string` SET `content_default`='Dir wird es gut gehen' WHERE (`entry`='2000000036'); /* You\'re going to be just fine. */
UPDATE `dbscript_string` SET `content_default`='Bis wir uns wiedersehen, tapfere Seele.' WHERE (`entry`='2000000042'); /* Until we meet again, brave one. */
UPDATE `dbscript_string` SET `content_default`='Es ist vollbracht...' WHERE (`entry`='2000000044'); /* It is done... */
UPDATE `dbscript_string` SET `content_default`='Es geht doch nichts über kochend heißes Morgengebräu an einem kalten Morgen in Dun Morogh! Danach kann der Tag kommen!' WHERE (`entry`='2000000045'); /* There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right! */
UPDATE `dbscript_string` SET `content_default`='Ooooh! Heiß! Heiß! Heiß! Wenn Euch das nicht auf Touren bringt, kann ich Euch auch nicht helfen!' WHERE (`entry`='2000000046'); /* Oooooo hot hot hot! If that won\'t put spring IN your step,I don\'t know what will! */
UPDATE `dbscript_string` SET `content_default`='Verflixt! Nein!!! Das kann... verflixt... nicht sein! Ihr habt mich... verflixt... mit Euren faulen Tricks betrogen! Verflixt!' WHERE (`entry`='2000000047'); /* Ribbit! No!! This cannot... ribbit... be! You have duped me with... ribbit... your foul trickery! Ribbit! */
UPDATE `dbscript_string` SET `content_default`='Lasst uns nun diese seltene Erde in meinen Pflanzbehälter füllen...' WHERE (`entry`='2000000048'); /* Now let us place this rare earth in my planter... */
UPDATE `dbscript_string` SET `content_default`='Ich danke Euch nochmals, $N. Diese seltene Erde wird mir bei meinen Experimenten von großem Nutzen sein.' WHERE (`entry`='2000000049'); /* Thank you again, $N. This rare earth will be very helpful in my experiments. */
UPDATE `dbscript_string` SET `content_default`='Hey, Belm! Gib mir einen Becher Donnerbräu Lager und einen für meinen guten Freund $N.' WHERE (`entry`='2000000056'); /* Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N. */
UPDATE `dbscript_string` SET `content_default`='Geister des Wassers, ich preise euch und erflehe einen Gefallen von euch. Ihr habt die Bitten gehört, die $N an euch gerichtet hat, und ich bin mir sicher, ihre Beweggründe sind lauter und edel. Bitte, helft uns.' WHERE (`entry`='2000000057'); /* Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s please, and I trust his inent is noble. Please, will you aid us? */
UPDATE `dbscript_string` SET `content_default`='Dank Euch, großer Geist. Danke!' WHERE (`entry`='2000000058'); /* Thank you great spirit. Thank you! */
UPDATE `dbscript_string` SET `content_default`='Ihr seid entlassen, $n.' WHERE (`entry`='2000000059'); /* You are dismissed, $N. */
UPDATE `dbscript_string` SET `content_default`='Folgt mir, guter Paladin. Ich werde Euer Pferdegeschirr schneller fertigen, als ich ein Zwergen - Starkbier hinunterspülen kann. Mmmm.... Starkbier.' WHERE (`entry`='2000000063'); /* Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout. */
UPDATE `dbscript_string` SET `content_default`='Nun, das sollte ausreichen. Komm jetzt, lasst uns zurück zum Laden gehen, um das Geschäft zu beenden!' WHERE (`entry`='2000000064'); /* Well, that should do it. Come now, back to the shop to finish our business! */
UPDATE `dbscript_string` SET `content_default`='Wir werden keinen Dämonen-Diener in unseren Ländern dulden!' WHERE (`entry`='2000000065'); /* We will suffer no demon\'s servant in our lands! */
UPDATE `dbscript_string` SET `content_default`='Friede und Geduld sei mit Euch, $N. Bleibt immer stark.' WHERE (`entry`='2000000066'); /* Peace and patience be with you, $N. Remain strong always. */
UPDATE `dbscript_string` SET `content_default`='%s versucht, Maurys Klumpfuß zu öffnen...' WHERE (`entry`='2000000067'); /* %s tries opening Maury\'s Clubbed Foot... */
UPDATE `dbscript_string` SET `content_default`='Pah! $N, dieser Fuß gibt nicht nach!' WHERE (`entry`='2000000068'); /* Bah! $N, this foot won\'t budge! */
UPDATE `dbscript_string` SET `content_default`='Danke, $N.' WHERE (`entry`='2000000069'); /* Thank you, $N. */
UPDATE `dbscript_string` SET `content_default`='Ich bin sicher, dass ich eine Verwendung für diese Mixtur finden werde...' WHERE (`entry`='2000000070'); /* I\'m sure I can find a use for this mixture... */
UPDATE `dbscript_string` SET `content_default`='Nochmals vielen Dank für Ihre Hilfe. Möge der Wind während Ihrer Reisen immer in Ihrem Rücken sein' WHERE (`entry`='2000000071'); /* Thank you again for your aid. May the wind always be at your back during your travels. */
UPDATE `dbscript_string` SET `content_default`='Das war einfacher als ich dachte... das Siegelzeichen von Thoradin ist endlich wieder ganz.' WHERE (`entry`='2000000072'); /* Easier than I expected... the sigil of Thoradin is whole, once again. */
UPDATE `dbscript_string` SET `content_default`='Wartet, $N!!! Es sieht so aus, als würden wir hier Hilfe brauchen...' WHERE (`entry`='2000000073'); /* Wait, $N!!! It looks like we\'re going to need some help here... */
UPDATE `dbscript_string` SET `content_default`='In den Kasten, meine Süßen! Genau so. Einer nach dem anderen.' WHERE (`entry`='2000000074'); /* Into the box me pretties! Thas it. One by one, ye go. */
UPDATE `dbscript_string` SET `content_default`='Hört her, Bewohner von Tanaris! Ihr sollt wissen, dass $n ein erhabenes Mitglied des Mithrilordens ist. Ein Schmied von Ehre, Hingabe und unendlicher Geduld. Ein dreifaches Hoch auf $n!' WHERE (`entry`='2000000076'); /* Hear ye, denizens of Tanaris! Let it be known $n is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $n */
UPDATE `dbscript_string` SET `content_default`='Hört her, Bewohner von Tanaris! Ihr sollt wissen, dass $n ein erhabenes Mitglied des Mithrilordens ist. Ein Schmied von Ehre, Hingabe und unendlicher Geduld. Ein dreifaches Hoch auf $n%s spürt, wie sein Blut in Wallung gerät und die Arglist des Raptors ihn durchströmt.' WHERE (`entry`='2000000077'); /* %s watches as his blood begins to stir, and the guile of the raptor slips through him. */
UPDATE `dbscript_string` SET `content_default`='Was ist das für eine Stärke, die mich durchfließt? Ist dies die Macht des Schamanismus, von der Torgan gesprochen hat...?' WHERE (`entry`='2000000078'); /* What is this power that flows through me? Is this the power of shamanism that Tor\'gan spoke of...? */
UPDATE `dbscript_string` SET `content_default`='Beeindruckend! Ich fühle mich... erneuert. Meine Kraft kehrt zurück!' WHERE (`entry`='2000000079'); /* Amazing! I feel... renewed. My strength returns! */
UPDATE `dbscript_string` SET `content_default`='%s beginnt einen Ritus der Erschaffung...' WHERE (`entry`='2000000080'); /* %s begins a rite of creation... */
UPDATE `dbscript_string` SET `content_default`='Ich habe das Totem erschaffen. Ihr, $N, müsst den Brunnen läutern.' WHERE (`entry`='2000000081'); /* I have created the totem. You, $N, must cleanse the well. */
UPDATE `dbscript_string` SET `content_default`='%s erschafft ein neues Totem...' WHERE (`entry`='2000000082'); /* %s creates a new totem... */
UPDATE `dbscript_string` SET `content_default`='Das Totem ist fertig, $N.' WHERE (`entry`='2000000083'); /* The totem is made, $N. */
UPDATE `dbscript_string` SET `content_default`='%s verwandelt die Gegenstände von $n in ein Totem der Läuterung...' WHERE (`entry`='2000000084'); /* %s transforms the items $N gave him into a totem of cleansing... */
UPDATE `dbscript_string` SET `content_default`='Das Totem ist fertig. Der Brunnen kann nun geläutert werden.' WHERE (`entry`='2000000085'); /* The totem is made. The well may now be cleansed. */
UPDATE `dbscript_string` SET `content_default`='%s betrachtet das Pergament aus dem Folianten der Schattenhammerkultisten...' WHERE (`entry`='2000000086'); /* %s studies the parchment from the Twilight Tome... */
UPDATE `dbscript_string` SET `content_default`='%s wird von freigesetzter Magie getroffen!' WHERE (`entry`='2000000087'); /* %s is struck by unleashed magic! */
UPDATE `dbscript_string` SET `content_default`='Hmmm...' WHERE (`entry`='2000000088'); /* Hmm... */
UPDATE `dbscript_string` SET `content_default`='Die Geister des Steinkrallengebirges wüten noch immer, $n.' WHERE (`entry`='2000000089'); /* The spirits of Stonetalon still rage, $N. */
UPDATE `dbscript_string` SET `content_default`='Ich fürchte, wir werden sie niemals beschwichtigen können...' WHERE (`entry`='2000000090'); /* I fear we may never soothe them... */
UPDATE `dbscript_string` SET `content_default`='%s hört sich die Bitte von $n an.' WHERE (`entry`='2000000091'); /* %s listens to $N\'s plea. */
UPDATE `dbscript_string` SET `content_default`='Ihr habt gut daran getan zu kommen. Meine Weisheit gehört Euch.' WHERE (`entry`='2000000092'); /* You were right to come. My wisdom will be yours. */
UPDATE `dbscript_string` SET `content_default`='Geht, mein Diener. Bringt Kunde vom Steinkrallengebirge zu Apothekerin Zamah.' WHERE (`entry`='2000000093'); /* Go, my servant. Send word of Stonetalon to Apothecary Zamah. */
UPDATE `dbscript_string` SET `content_default`='%s übergibt Apothekerin Zamah eine Nachricht.' WHERE (`entry`='2000000094'); /* %s gives message to Apothecary Zamah. */
UPDATE `dbscript_string` SET `content_default`='%s lächelt.' WHERE (`entry`='2000000095'); /* %s smiles. */
UPDATE `dbscript_string` SET `content_default`='%s erschafft sein Toxin...' WHERE (`entry`='2000000096'); /* %s creates his toxin... */
UPDATE `dbscript_string` SET `content_default`='Da wären wir, $n. Das Toxin steht bereit.' WHERE (`entry`='2000000097'); /* There we are, $N. The toxin is ready. */
UPDATE `dbscript_string` SET `content_default`='%s füllt einen Behälter mit dem Toxin.' WHERE (`entry`='2000000098'); /* %s fills a container with the toxin. */
UPDATE `dbscript_string` SET `content_default`='Das Toxin ist fertig, $n.' WHERE (`entry`='2000000099'); /* %s The toxin is ready, $N. */
UPDATE `dbscript_string` SET `content_default`='%s stellt die Kiste mit den Teilen auf den Boden.' WHERE (`entry`='2000000100'); /* %s places the crate of parts on the ground. */
UPDATE `dbscript_string` SET `content_default`='%s greift sich ein Teil und steckt es in die Tasche...' WHERE (`entry`='2000000101'); /* %s grabs a part and puts it in his pocket... */
UPDATE `dbscript_string` SET `content_default`='So, das sollte reichen...' WHERE (`entry`='2000000102'); /* There, that should do it... */
UPDATE `dbscript_string` SET `content_default`='%s saugt etwas Traumstaub in die Nase...' WHERE (`entry`='2000000103'); /* %s snorts a speck of dream dust up his nose... */
UPDATE `dbscript_string` SET `content_default`='%s ist benommen...' WHERE (`entry`='2000000104'); /* %s is dazed... */
UPDATE `dbscript_string` SET `content_default`='HATSCHI!' WHERE (`entry`='2000000105'); /* ACHOO! */
UPDATE `dbscript_string` SET `content_default`='Unglaublich! $n, dieser Traumstaub ist aber ein Teufelszeug!' WHERE (`entry`='2000000106'); /* Wow! $N, that dream dust is powerful stuff! */
UPDATE `dbscript_string` SET `content_default`='He, $n! Vergesst nicht, eine Kiste, ein Handbuch und einen Leitstecken mitzunehmen!' WHERE (`entry`='2000000107'); /* Hey $N! Don\'t forget to grab a crate, a manual and a command stick! */
UPDATE `dbscript_string` SET `content_default`='%s beginnt zu tanzen.' WHERE (`entry`='2000000108'); /* %s begins to dance. */
UPDATE `dbscript_string` SET `content_default`='Haha! $n, Ihr seid mir schon ein Partner!' WHERE (`entry`='2000000109'); /* Hahah! $N, you make quite a partner! */
UPDATE `dbscript_string` SET `content_default`='%s beginnt, über den Herzen und Zungen einen Zauber zu sprechen.' WHERE (`entry`='2000000110'); /* %s begins to cast a spell over the hearts and tongues. */
UPDATE `dbscript_string` SET `content_default`='Die Brut von Onyxia!' WHERE (`entry`='2000000111'); /* The brood of Onyxia! */
UPDATE `dbscript_string` SET `content_default`='Okay, Leute. Macht euch an die Arbeit und bringt diese Knochen an.' WHERE (`entry`='2000000112'); /* Okay, crew. Get to work on getting these bones installed. */
UPDATE `dbscript_string` SET `content_default`='Ich brauche nur wenige Minuten, um das Serum zuzubereiten, $n.' WHERE (`entry`='2000000113'); /* The serum will only take a few minutes to prepare, $N. */
UPDATE `dbscript_string` SET `content_default`='Fast fertig...' WHERE (`entry`='2000000114'); /* Almost done... */
UPDATE `dbscript_string` SET `content_default`='Endlich ist das Serum vollendet, $n. Kommt jetzt näher. Wir müssen reden.' WHERE (`entry`='2000000115'); /* At last, the serum is complete, $N. Now, come closer. We must talk. */
UPDATE `dbscript_string` SET `content_default`='%s trinkt einen großen Schluck Bier.' WHERE (`entry`='2000000116'); /* %s takes big swig of ale. */
UPDATE `dbscript_string` SET `content_default`='Das war erfrischend. Jetzt zu den Informationen, die ich loswerden muss...' WHERE (`entry`='2000000117'); /* That was refreshing. Now there\'s information that needs to be told... */
UPDATE `dbscript_string` SET `content_default`='Ich denke, dass die Verlassenen die Verbündeten der Horde in die Irre führen... wartet... Ich fühle mich so... benommen...' WHERE (`entry`='2000000118'); /* I believe the Forsaken are misleading the allies of the Horde... wait... I feel so... dizzy... */
UPDATE `dbscript_string` SET `content_default`='%s windet sich vor Schmerzen.' WHERE (`entry`='2000000119'); /* %s writhes in pain. */
UPDATE `dbscript_string` SET `content_default`='AAAAAAAARGH!' WHERE (`entry`='2000000120'); /* AAAAAAAAAAAAAAAARGH */
UPDATE `dbscript_string` SET `content_default`='Hiermit zerstöre ich diese Instrumente des Bösen! Für die Horde!' WHERE (`entry`='2000000121'); /* I hereby destroy these instruments of evil! For the Horde! */
UPDATE `dbscript_string` SET `content_default`='Bitte folgt mir.' WHERE (`entry`='2000000122'); /* Please, follow me. */
UPDATE `dbscript_string` SET `content_default`='Ich habe noch nicht herausgefunden, was es genau ist, aber irgendetwas an den heißen Quellen ist seltsam...' WHERE (`entry`='2000000123'); /* I haven\'t really figured out what it is, but there\'s something strange about the hot springs... */
UPDATE `dbscript_string` SET `content_default`='%s wirft das Schwert in den seichten Teich.' WHERE (`entry`='2000000124'); /* %s tosses the sword into the shallow pool. */
UPDATE `dbscript_string` SET `content_default`='Ich habe etwas festgestellt. Immer, wenn ich etwas in dieses Wasser werfe, dann hat es sich geradezu unvorstellbar zu seinem Vorteil verändert, wenn ich es wieder heraushole.' WHERE (`entry`='2000000125'); /* I\'ve found that when I throw something into this water, it has improved incredibly when I retrieve it. */
UPDATE `dbscript_string` SET `content_default`='Na, was auch immer der Grund dafür sein mag, es funktioniert jedenfalls wunderbar!' WHERE (`entry`='2000000126'); /* Well, whatever it is, it works quite well! */
UPDATE `dbscript_string` SET `content_default`='Und ich bin fest entschlossen, mehr herauszufinden... Solltet Ihr also meine Hilfe wieder benötigen, dann wisst Ihr ja, wo Ihr mich finden könnt.' WHERE (`entry`='2000000127'); /* And I am determined to find out more... So if you need my help again, you know where I\'ll be. */
UPDATE `dbscript_string` SET `content_default`='Ehret Eure Helden! Heute haben sie einem unserer verhasstesten Feinde einen schweren Schlag beigebracht! Rend Schwarzfaust, der falsche Kriegshäuptling, ist gefallen!' WHERE (`entry`='2000000128'); /* Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen! */
UPDATE `dbscript_string` SET `content_default`='Badet in meiner Macht! Trinkt meine Kraft! Kämpft zum Ruhm der Horde!' WHERE (`entry`='2000000129'); /* Be bathed in my power! Drink in my might! Battle for the glory of the Horde! */
UPDATE `dbscript_string` SET `content_default`='Diese Urkunden gehören mir, Bruder! Bald schon werdet Ihr mir nicht mehr im Wege stehen!' WHERE (`entry`='2000000130'); /* The deeds are mine, brother! Soon you shall be out of my way for good! */
UPDATE `dbscript_string` SET `content_default`='Oh Mann, ich dachte wirklich, dass das mein sicheres Ende gewesen sei. Ugh... bin noch ganz benommen...' WHERE (`entry`='2000000131'); /* Oh man, I thought I was dead for sure. Ugh... still dizzy... */
UPDATE `dbscript_string` SET `content_default`='Ich denke, ich komme alleine zur Festung zurück. Jetzt, da Ihr mir Zeit verschafft habt, dürfte ich mich herausschleichen können. Wer immer Ihr auch sein mögt...danke. Möge Elune Euch stets segnen!' WHERE (`entry`='2000000132'); /* I can get back to the Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always! */
UPDATE `dbscript_string` SET `content_default`='Das dürfte nicht lange dauern...' WHERE (`entry`='2000000133'); /* This shouldn\'t take long... */
UPDATE `dbscript_string` SET `content_default`='Der Unsichtbarkeitsschnaps steht für Euch bereit, $n.' WHERE (`entry`='2000000134'); /* The invisibility liquor is ready for you, $n */
UPDATE `dbscript_string` SET `content_default`='Das geht runter wie Nichts...' WHERE (`entry`='2000000135'); /* Here goes nothing... */
UPDATE `dbscript_string` SET `content_default`='Corbett, mein Teurer. Harlan benötigt so schnell wir können eine Ladung gestrickter Hemden und Hosen.' WHERE (`entry`='2000000139'); /* Corbett, dear. Harlan needs a load of knitted shirts and pants as soon as we can manage. */
UPDATE `dbscript_string` SET `content_default`='Corbett, seid Ihr da? Harlan benötigt noch eine Ladung Strickwaren. Könnt Ihr sie ihm bringen?' WHERE (`entry`='2000000140'); /* Corbett, you there? Harlan needs another load of knitted goods. Can you take it to him? */
UPDATE `dbscript_string` SET `content_default`='Es war mir ein Vergnügen, Zuckerschnute. Ich bin bald zurück...' WHERE (`entry`='2000000141'); /* My pleasure, sugar drop. I\'ll be back soon... */
UPDATE `dbscript_string` SET `content_default`='Die Geschäfte im Basar scheinen ja gut zu laufen. Ich werde ihm sofort Nachschub bringen!' WHERE (`entry`='2000000142'); /* Business must be good down at the bazaar. I\'ll get him resupplied right away! */
UPDATE `dbscript_string` SET `content_default`='Hm... wenn ich das hier losgeworden bin, werde ich vielleicht in dieses Käsegeschäft gehen und mir dort einen kleinen Imbiss genehmigen.' WHERE (`entry`='000000143'); /* Hm... after dropping this off, I think I\'ll head to that cheese shop for a snack. */
UPDATE `dbscript_string` SET `content_default`='Ich müsste doch ein paar Münzen bei diesem Geschäft verdient haben. Vielleicht kaufe ich mir ein Mittagessen...' WHERE (`entry`='2000000144'); /* I should have a few extra coins from this sale. Maybe I\'ll buy myself some lunch... */
UPDATE `dbscript_string` SET `content_default`='He, Harlan. Hier ist eine Ladung Strickstoff für Euch.' WHERE (`entry`='2000000145'); /* Hey Harlan. Here\'s a load of knitted cloth for you. */
UPDATE `dbscript_string` SET `content_default`='Uff! Hier ist eine neue Ladung an Vorräten, Harlan. Euer Geschäft scheint ja gut zu laufen!' WHERE (`entry`='2000000146'); /* Oomph! Here\'s a load of supplies. It must be selling fast! */
UPDATE `dbscript_string` SET `content_default`='Ah ja, und pünktlich geliefert. Es ist wie immer ein Vergnügen, mit Euch Geschäfte zu machen, Corbett.' WHERE (`entry`='2000000147'); /* Ah yes, and promptly delivered. As always, it\'s a pleasure doing business with you, Corbett. */
UPDATE `dbscript_string` SET `content_default`='Ah, das weiß ich sehr zu schätzen, Corbett. Wir werden alles sofort in die Regale räumen.' WHERE (`entry`='2000000148'); /* Ahh, much appreciated, Corbett. We\'ll get these on the racks immediately. */
UPDATE `dbscript_string` SET `content_default`='Schön zu sehen, dass es Euch so gut geht, Harlan. Und ich hoffe, wir sehen uns bald wieder...' WHERE (`entry`='2000000149'); /* Glad to see you\'re doing so well, Harlan. And I hope to see you again soon? */
UPDATE `dbscript_string` SET `content_default`='Dann will ich mal wieder. Macht\'s gut, Harlan.' WHERE (`entry`='2000000150'); /* Well, I am off than. Take care, Harlan! */
UPDATE `dbscript_string` SET `content_default`='Nun zu diesem Imbiss...' WHERE  (`entry`='2000000151'); /* content: Now for that snack... */
UPDATE `dbscript_string` SET `content_default`='Hallo, Triasklan! Eine Kugel von Eurem geräucherten Mozzarella, bitte!' WHERE (`entry`='2000000152'); /* Hullo, Trias clan! A ball of your smoked mozzarella, if you please! */
UPDATE `dbscript_string` SET `content_default`='Guten Tag, Elling! Hallo Elaine! Kann ich einen Laib Blaukäse bekommen?' WHERE (`entry`='2000000153'); /* Good day. Elling! Hullo Elaine! Let me have a wheel of blue cheese, eh? */
UPDATE `dbscript_string` SET `content_default`='Guten Tag, Corbett. Hier ist Euer Käse. Heute Morgen ganz frisch gemacht! Und wie läuft Euer Laden?' WHERE (`entry`='2000000154'); /* Good day, Corbett. Here\'s your cheese, fresh made this morning! And how are things at your shop? */
UPDATE `dbscript_string` SET `content_default`='Hallo, Corbett! Bitte sehr! Sehe ich es richtig, dass Euer Tuchladen gut läuft...?' WHERE (`entry`='2000000155'); /* Hi Corbett! Here, you go! I trust business is faring well at your clothier shop...? */
UPDATE `dbscript_string` SET `content_default`='Ja, gnädige Frau, das Geschäft läuft gut!' WHERE (`entry`='2000000156'); /* Yes ma\'am, business is brisk! */
UPDATE `dbscript_string` SET `content_default`='Danke für den Käse!' WHERE (`entry`='2000000157'); /* Thanks for the cheese! */
UPDATE `dbscript_string` SET `content_default`='Zeit, wieder zurück in den Laden zu gehen...' WHERE (`entry`='2000000158'); /* Time to get back to the shop... */
UPDATE `dbscript_string` SET `content_default`='Ich bin zurück!' WHERE (`entry`='2000000159'); /* I\'m back! */
UPDATE `dbscript_string` SET `content_default`='Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE (`entry`='2000000160'); /* Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul */
UPDATE `dbscript_string` SET `content_default`='Aaarrrrr!!' WHERE (`entry`='2000000161'); /* ROARRRRR!! */
UPDATE `dbscript_string` SET `content_default`='DUNKELHAIN... ICH HUNGER!!' WHERE (`entry`='2000000162'); /* DARKSHIRE... I HUNGER!! */
UPDATE `dbscript_string` SET `content_default`='Wildherzen Euch töten, wenn Ihr zurück kommt. Ihr hier nicht mehr willkommen!' WHERE (`entry`='2000000163'); /* I said GOOD DAY! */
UPDATE `dbscript_string` SET `content_default`='Mein Schwert Archeus hat mir in meinem Leben gut gedient. Aber nun, da mein Geist mein glückloses Dasein verlässt, brauche ich es nicht länger.' WHERE (`entry`='2000000164'); /* My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer. */
UPDATE `dbscript_string` SET `content_default`='Ich werde mich an die Liebe meiner Tochter klammern und hoffen, dass mir im Licht meine Sünden vergeben werden.' WHERE (`entry`='2000000165'); /* I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins. */
UPDATE `dbscript_string` SET `content_default`='OH NEIN! Der König is tot! Eh... lang lebe der neue König! Jo!' WHERE (`entry`='2000000166'); /* OH NOES! Da king is dead! Uh... hail to da new king! Yeah! */
UPDATE `dbscript_string` SET `content_default`='Yar, er ist jetzt tot. Das macht Euch den neue König... äh, Euch alle! Gordok gehören jetzt Euch, Boss! Wenn Ihr lernen wollt, was König alles machen kann, fragen mich. Ich war... Berater! Jaha, darum mich alle nennen der Gewiefte!' WHERE (`entry`='2000000167'); /* Yar, he\'s dead all right. That makes you da new king... well, all of you! Gordok is yours now, boss! You should talk to me so you can learn everything there is about being da king! I was... is his assistant! Yeah, that\'s why I\'m called da crafty one! */
UPDATE `dbscript_string` SET `content_default`='%s starrt nach Nordwesten und lässt ein langes, herausgezogenes Heulen von sich.' WHERE (`entry`='2000000168'); /* %s stares to the northwest and lets out a long, drawn out howl. */
UPDATE `dbscript_string` SET `content_default`='%s lässt ein mächtiges Heulen von sich.' WHERE (`entry`='2000000169'); /* %s lets forth a mighty howl. */
UPDATE `dbscript_string` SET `content_default`='Wie Ihr befehlt!' WHERE (`entry`='2000000170'); /* By your command */
UPDATE `dbscript_string` SET `content_default`='Wartet hier, $n. Der Spionagebot wird Lescovar schnellstens herauslocken. Seid bereit! Greift erst an, wenn Ihr das Gespräch mitgehört habt.' WHERE (`entry`='2000000171'); /* Wait here, $N. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you\'ve overheard their conversation. */
UPDATE `dbscript_string` SET `content_default`='Einen guten Tag Euch beiden. Ich möchte Lord Lescovar sprechen.' WHERE (`entry`='2000000172'); /* Good day to you both. I would speak to Lord Lescovar */
UPDATE `dbscript_string` SET `content_default`='Natürlich. Er erwartet Euch in der Bibliothek.' WHERE (`entry`='2000000173'); /* Of course. He awaits you in the library */
UPDATE `dbscript_string` SET `content_default`='Danke. Das Licht sei mit Euch beiden.' WHERE (`entry`='2000000174'); /* Thank you. The Light be with you both. */
UPDATE `dbscript_string` SET `content_default`='Mylord, Euer Gast ist da. Er erwartet Euch.' WHERE (`entry`='2000000175'); /* Milord, your guest has arrived. He awaits your presence. */
UPDATE `dbscript_string` SET `content_default`='Ah, vielen Dank. Bleibt hier in der Bibliothek, während ich mich um diese kleine Angelegenheit kümmere.' WHERE (`entry`='2000000176'); /* Ah, thank you kindly. I will leave you to the library while I tend to this small matter. */
UPDATE `dbscript_string` SET `content_default`='Ich werde die Zeit zu nutzen wissen, Mylord. Danke.' WHERE (`entry`='2000000177'); /* I shall use this time wisely, milord. Thank you. */
UPDATE `dbscript_string` SET `content_default`='Es ist Zeit für meine Meditation, lasst mich allein.' WHERE (`entry`='2000000178'); /* It\'s time for my meditation, leave me. */
UPDATE `dbscript_string` SET `content_default`='Ja, Sire!' WHERE (`entry`='2000000179'); /* Yes, sir! */
UPDATE `dbscript_string` SET `content_default`='%s wartet, bis die Wachen außer Sichtweite sind.' WHERE (`entry`='2000000180'); /* %s waits for the guards to be out of sight. */
UPDATE `dbscript_string` SET `content_default`='Da seid Ihr ja. Was gibt es für Neuigkeiten aus Westfall?' WHERE (`entry`='2000000181'); /* There you are. What news from Westfall? */
UPDATE `dbscript_string` SET `content_default`='Van Cleef lässt mitteilen, dass die Pläne unterwegs seien. Doch er hat Gerüchte vernommen, dass irgendjemand herumschnüffelt.' WHERE (`entry`='2000000182'); /* VanCleef sends word that the plans are underway. But he\'s heard rumors about someone snooping about. */
UPDATE `dbscript_string` SET `content_default`='Hmm, das könnte dieser Schnüffler Shaw sein. Ich werde sehen, was ich herausfinden kann. Und nun fort mit Euch. Ich werde Euch bald wieder aufsuchen.' WHERE (`entry`='2000000183'); /* Hmm, it could be that meddler Shaw. I will see what I can discover. Be off with you. I\'ll contact you again soon. */
UPDATE `dbscript_string` SET `content_default`='Wohlan denn. Dann werde ich zurückkehren.' WHERE (`entry`='2000000184'); /* Very well. I will return then. */
UPDATE `dbscript_string` SET `content_default`='Das ist es! Darauf habt Ihr gewartet! TÖTET SIE!' WHERE (`entry`='2000000185'); /* That\'s it! That\'s what you were waiting for! KILL THEM! */
UPDATE `dbscript_string` SET `content_default`='Verteidigt euch, Dummkopf!' WHERE (`entry`='2000000186'); /* Defend yourself, fool! */
UPDATE `dbscript_string` SET `content_default`='Die Monstrosität ist in das Lager der Nachtwache eingefallen! Schnell, wir müssen sie abfangen, bevor sie die Stadt erreicht!' WHERE (`entry`='2000000187'); /* The abomination has overrun the Night Watch camp! Quickly, we must intercept it before it reaches town! */
UPDATE `dbscript_string` SET `content_default`='Die Bestie wurde erschlagen! Jetzt herrscht wieder Ruhe in Dunkelhain!' WHERE (`entry`='2000000188'); /* The beast is slain! All is well in Darkshire. */
UPDATE `dbscript_string` SET `content_default`='Stacheleberfetzen! Die dürften den Zweck erfüllen. Fische lieben Stacheleber.' WHERE (`entry`='2000000189'); /* Quillboar scraps! These should do the trick. Fish love Quillboar. */
UPDATE `dbscript_string` SET `content_default`='Hab einen gefangen! Werde mal sehen, ob eine der Wachen hungrig ist. Komm mit Reißzahn!' WHERE (`entry`='2000000190'); /* Caught one! I\'ll see if any of the guards are hungry. Come on Fang! */
UPDATE `dbscript_string` SET `content_default`='Falls Ihr hungrig sein solltet, ich habe einen Fisch gefangen...' WHERE (`entry`='2000000191'); /* I caught a fish if you are hungry... */
UPDATE `dbscript_string` SET `content_default`='Das nenne ich einen guten Fang! Ihr ehrt die Horde, Junge, wir danken dir!' WHERE (`entry`='2000000192'); /* A nice catch it is at that! You bring honor to the Horde boy, We thank you! */
UPDATE `dbscript_string` SET `content_default`='Wie Ihr wünscht...' WHERE (`entry`='2000000195'); /* As you wish... */
UPDATE `dbscript_string` SET `content_default`='Ich bezweifle stark, dass er irgendwas dazu zu sagen hat, Fremder...' WHERE (`entry`='2000000196'); /* I very much doubt that he will have anything to say, stranger... */
UPDATE `dbscript_string` SET `content_default`='Ich persönlich hatte kein Problem mit ihm. Es war der Prinz, der an ihm als Hochelf ein Exempel statuieren ließ. Leider bin ich nicht derjenige, der den Prinzen in Frage stellen kann. Zur seiner Verteidigung muss ich noch anmerken, dass er Meister Winthalus nicht sofort einäschern ließ.' WHERE (`entry`='2000000197'); /* 'I personally didn\'t mind him. It was the Prince who took exception to a high elf in his domain. Alas, I am not one to question the Prince. In his defense, he did not incinerate Master Winthalus immediately. */
UPDATE `dbscript_string` SET `content_default`='Wir möchten nicht, dass noch irgendjemand auf uns aufmerksam wird, Fremder. Kehrt zu denen zurück, die Euch hierher geschickt haben, und sagt ihnen, dass Ihr nichts finden konntet. Wenn Ihr das getan habt (und ich werde erfahren, ob Ihr meinen Rat befolgt habt), kehrt zu mir zurück, und ich werde Euch über das Schicksal der Verstorbenen aufklären.' WHERE (`entry`='2000000198'); /* We most definitely do not need any more attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased. */
UPDATE `dbscript_string` SET `content_default`='Hmmm... ich glaube ich brauche einen besseren Köder. Ich werde mal im Wagen meines Vaters nachsehen.' WHERE (`entry`='2000000201'); /* Hmmm... I think I need better bait. I\'ll check my father\'s wagon. */
UPDATE `dbscript_string` SET `content_default`='Was? $n, Ihr habt mir gut gedient, aber...' WHERE (`entry`='2000000234'); /* What? $N, you served me well, but... */
UPDATE `dbscript_string` SET `content_default`='Warum habt Ihr mich so früh beschworen? Ich habe meine volle Macht noch nicht erreicht!' WHERE (`entry`='2000000235'); /* Why have you summoned me so soon? I haven\'t yet reached my full power! */
UPDATE `dbscript_string` SET `content_default`='Einerlei. Ihr wart dumm genug, mir zu helfen, und jetzt werdet Ihr dafür bezahlen!' WHERE (`entry`='2000000236'); /* No matter. You were a fool to help me, and now you will pay! */
UPDATE `dbscript_string` SET `content_default`='Nochmals danke, $n. Ich werde jetzt einfach hier warten, bis ich ungefährdet gehen kann.' WHERE (`entry`='2000000237'); /* Thank again, $n.  Now I\'ll just wait here until it\'s safe to leave. */
UPDATE `dbscript_string` SET `content_default`='Die Anzahl meiner Gefährten schwindet, Göttin, und meine eigene Macht wird bald nicht mehr ausreichen, die Dämonen des Teufelswaldes zurückzuhalten.' WHERE (`entry`='2000000238'); /* The numbers of my companions dwindles, goddess, and my own power shall soon be insufficient to hold back the demons of Felwood. */
UPDATE `dbscript_string` SET `content_default`='Göttin, gewähre mir die Stärke, meine Feinde zu besiegen! Hör mich bitte an, ich bin verzweifelt in meiner Not und meine Sache ist gerecht!' WHERE (`entry`='2000000239'); /* Goddess, grant me the power to overcome my enemies! Hear me, please, my need is desperate and my cause is just! */
UPDATE `dbscript_string` SET `content_default`='Was... was ist das? Könnte das die Antwort auf meine Gebete sein? Elune hat mir eine Waffe gewährt - diese Sense -, um die Dämonen zu besiegen.' WHERE (`entry`='2000000240'); /* What... what is this? Could this by the answer to my prayers? Elune has granted me a weapon -- this scythe -- to defeat the demons. */
UPDATE `dbscript_string` SET `content_default`='Ich habe versagt... Ich habe in meiner Pflicht versagt... habe mein Volk enttäuscht... Die Worgs sind wild und die Sense meiner Göttin ist verloren.' WHERE (`entry`='2000000241'); /* I have failed... I have failed in my duty... failed my people... The worgen run rampant, and the Scythe of my goddess is lost. */
UPDATE `dbscript_string` SET `content_default`='Das Böse, das ich entfesselt habe... In wessen Hand mag die Stärke, die meine Göttin mir gewährte, nun liegen?... Wessen Hand führt sie nun?' WHERE (`entry`='2000000242'); /* This evil I have unleashed... In whose hand does the power my goddess granted to me now lie... By whose hand is it directed? */
UPDATE `dbscript_string` SET `content_default`='Terenthis, Raene schickte mich, um Euch zu suchen. Die Schildwachen des Eschentals brauchen Hilfe.' WHERE (`entry`='2000000260'); /* Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale. */
UPDATE `dbscript_string` SET `content_default`='Die Macht der Träne der Monde gehört jetzt mir! Mir ganz allein!' WHERE (`entry`='2000000345'); /* The power of the Tear of the Moons is mine! Mine I say! */
UPDATE `dbscript_string` SET `content_default`='%s beginnt, die Träne der Monde zu reiben.' WHERE (`entry`='2000000346'); /* %s begins to rub the Tear of the Moons. */
UPDATE `dbscript_string` SET `content_default`='Macht! Glorreiche Macht!' WHERE (`entry`='2000000347'); /* Power! Glorious power! */
UPDATE `dbscript_string` SET `content_default`='%s beginnt, seltsame Grunzgeräusche von sich zu geben. Die Träne der Monde fällt zu Boden und zerspringt.' WHERE (`entry`='2000000348'); /* %s begins to make strange grunting noises. The Tear of the Moons drops to the ground and shatters. */
UPDATE `dbscript_string` SET `content_default`='Spendet den Wohltätigkeitsorganisationen, die den Opfern dieser schweren Zeit zu helfen versuchen! Bitte.' WHERE (`entry`='2000000349'); /* Give to the charities who seek to help the victims of these hard times! Please. */
UPDATE `dbscript_string` SET `content_default`='Vergesst nicht die Waisen aus Sturmwind!' WHERE (`entry`='2000000350') /* Don\'t forget the orphans of Stormwind! */
UPDATE `dbscript_string` SET `content_default`='Gebt von Herzen und aus vollen Taschen! Gebt für die Kinder aus Sturmwind, die ihre Eltern verloren haben.' WHERE (`entry`='2000000351') /* Give of your hearts and your purses! Give to the children of Stormwind who have lost their parents. */
UPDATE `dbscript_string` SET `content_default`='Helft den Kindern aus Sturmwind... den Opfern des Krieges und der Seuche!' WHERE (`entry`='2000000352') /* Help the children of Stormwind... victims of the war and plague! */

UPDATE `dbscript_string` SET `content_default`='Kommt, $n. Der See befindet sich direkt hinter der nächsten Biegung.' WHERE (`entry`='2000000375'); /* Come,  $N. The lake is around the bend. */
UPDATE `dbscript_string` SET `content_default`='Bleibt in meiner Nähe, $n. Ich werde Euch beschützen, falls etwas schief geht.' WHERE (`entry`='2000000376'); /* Stand near me,  $N. I will protect you should anything go wrong. */
UPDATE `dbscript_string` SET `content_default`='Malfurion!' WHERE (`entry`='2000000377'); /* Malfurion! */
UPDATE `dbscript_string` SET `content_default`='Remulos, mein alter Freund. Es ist schön, Euch wiederzusehen. Ich wusste, dass meine Botschaft Euch erreichen würde, auf dem einen oder auf dem anderen Weg.' WHERE (`entry`='2000000378'); /* Remulos,  old friend. It is good to see you once more. I knew the message would find its way to you - one way or another. */
UPDATE `dbscript_string` SET `content_default`='Alles ist von schrecklichen Alpträumen durchzogen, Malfurion. Was geht im Smaragdgrünen Traum nur vor? Was könnte ihn derartig grausam verzerren?' WHERE (`entry`='2000000379'); /* It was shrouded in nightmares,  Malfurion. What is happening in the Dream? What could cause such atrocities? */
UPDATE `dbscript_string` SET `content_default`='Ich fürchte das Schlimmste, alter Freund. Innerhalb des Smaragdgrünen Traums bekämpfen wir einen neuen Feind, geboren aus uraltem Bösen. Yseras edle Brut ist den uralten Einflüsterungen erlegen. Es scheint, als sei es dem Alptraum gelungen die Grenzen der Traumwelt zu durchbrechen, um sich in Azeroth einen neuen Wirt zu suchen.' WHERE (`entry`='2000000380'); /* I fear for the worst,  old friend. Within the Dream we fight a new foe,  born of an ancient evil. Ysera\'s noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm to find a new host on Azeroth. */
UPDATE `dbscript_string` SET `content_default`='Ich habe es auch gespürt, Malfurion. Dunkle Zeiten werfen ihre Schatten voraus.' WHERE (`entry`='2000000381'); /* I sensed as much,  Malfurion. Dark days loom ahead. */
UPDATE `dbscript_string` SET `content_default`='Ja, Remulos. Die sterblichen Völker müssen auf das Kommende vorbereitet werden.' WHERE (`entry`='2000000382'); /* Aye Remulos,  prepare the mortal races. */